### ISSUE TITLE
Error Compilation.

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#10]
hello @trunkmaster, I have the following compilation error. https://github.com/trunkmaster/nextspace/commit/3c0e7c59513f1197a6cb075a95f0c3ccf51d3743

 Compiling file Operations/BGOperation.m ...
 Compiling file Operations/Mounter.m ...
 Compiling file Operations/ProcessManager.m ...
 Compiling file Operations/Sizer.m ...
 Compiling file Operations/FileMover.m ...
 Compiling file Processes/Processes.m ...
 Compiling file Processes/FileMoverUI.m ...
 Compiling file Processes/BGProcess.m ...
 Linking app Workspace ...
./obj/Workspace.obj/WindowMaker/src/wsmap.c.o: In function `workspace_map_realize':
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:219: undefined reference to `WMSetWidgetBackgroundPixmap'
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:230: undefined reference to `WMSetWidgetBackgroundPixmap'
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:233: undefined reference to `WMSetWidgetBackgroundPixmap'
./obj/Workspace.obj/WindowMaker/src/wsmap.c.o: In function `selected_workspace_callback':
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:147: undefined reference to `WMGetButtonText'
./obj/Workspace.obj/WindowMaker/src/wsmap.c.o: In function `update_mini_workspace':
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:456: undefined reference to `WMSetWidgetBackgroundPixmap'
/home/usertest/nextspace/Applications/Workspace/WindowMaker/src/wsmap.c:459: undefined reference to `WMSetWidgetBackgroundPixmap'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [Workspace.app/./Workspace] Error 1
gmake[3]: *** [internal-app-run-compile-submake] Error 2
gmake[2]: *** [Workspace.all.app.variables] Error 2
gmake[1]: *** [internal-all] Error 2
make: *** [internal-all] Error 2

**Comment by trunkmaster** [comment]
hello @armm77, 
Perhaps you have original WindowMaker's WINGs library installed on the system.
Remove it and try again.

**Comment by armm77** [comment]
It is correct, it has installed the libraries. Delete them and compile correctly.
