### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#11]
Hello @trunkmaster , this error appears to me with your last arrangements.

 Linking tool FileMover.tool ...
/usr/NextSpace/lib/libNXSystem.so: undefined reference to `__objc_class_name_NSColor'
/usr/NextSpace/lib/libNXSystem.so: undefined reference to `NSDeviceRGBColorSpace'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[5]: *** [obj/FileMover.tool] Error 1
gmake[4]: *** [internal-tool-all_] Error 2
gmake[3]: *** [FileMover.tool.all.tool.variables] Error 2
gmake[2]: *** [internal-all] Error 2
gmake[1]: *** [internal-all] Error 2
make: *** [internal-all] Error 2

**Comment by armm77** [comment]
I close the ticket because it was solved.

**Comment by armm77** [comment]
hello @trunkmaster, I return to open the ticket because the same error arose again.

**Comment by trunkmaster** [comment]
Confirmed. I'll look into it.

**Comment by trunkmaster** [comment]
@armm77, fixed in master branch (see the latest commit for description). Thank you for report.

**Comment by armm77** [comment]
already compiles correctly, thank you very much, @trunkmaster
