### ISSUE TITLE
The Screen Module fails.

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#12]
Selecting the screen option automatically closes the preferences.

**Comment by trunkmaster** [comment]
I forgot to adopt last change to NXScreen to Screen module preferences. Fixed in master branch. Thank you, @armm77.

**Comment by armm77** [comment]
@trunkmaster send an email to the account stoyan@on.com.ua is still active ..?

**Comment by trunkmaster** [comment]
@armm77, no it's very outdated. send me mail to stoyan255@gmail.com or stoyan255@ukr.net.

**Comment by trunkmaster** [comment]
@armm77, can I close issue?

**Comment by armm77** [comment]
Sorry, if we can close it, the incident was solved.
