### ISSUE TITLE
Minor Corrections to Build and Install Guide wiki page

### ISSUE THREAD

**Issue by paddle-to-the-sea** [trunkmaster/nextspace#129]
Re: "3. Build NEXTSPACE: 5. Take this step if you want GNUstep libraries with fresh patches:"
`$ patch -p0 < gnustep-gui-*.patch` and `$ patch -p0 < gnustep-back-*.patch`

I had to run zsh to get these two commands to run. Running the commands as given under bash yields: `-bash: gnustep-gui-*.patch: ambiguous redirect`

The commands work great under zsh!

Thanks!

**Comment by trunkmaster** [comment]
@paddle-to-the-sea, fixed in step 3.1 of wiki guide. Thank you.
