### ISSUE TITLE
Communication Methods

### ISSUE THREAD

**Issue by ghost** [trunkmaster/nextspace#13]
Is there an IRC channel, mailing list or a similar platform on which one can work together?

I very much like the scope and goals that you have set and agree with them completely.

**Comment by armm77** [comment]
hi @eukara, for the moment there is only this, when the number of users and developers grows, perhaps some system will be implemented so that there is better communication.

**Comment by eukara** [comment]
Well, as some words of encouragement, me and a few other people are very grateful that someone is working on a proper GNUstep desktop environment and we are eager to develop software taking advantage of the NX frameworks. 

Coming from a different part of the software industry (game-development) I've got a lot of my own ideas for platforms to become viable and I'd love to share those and contribute in any way I can to help get the platform to become more mature.

**Comment by armm77** [comment]
well @eukara, feel free to upload all the improvements and stabilizations that you want, the main thing is to get 100% functionality that @trunkmaster says https://github.com/trunkmaster/nextspace#status-of-implementaion

**Comment by trunkmaster** [comment]
hi @eukara,
As @armm77 have already said (BTW thank you, @armm77 ) it is the only place I do development, documentation and bug/issue tracking. For the moment, I perceive NEXTSPACE as a personal project. Although I'll be glad if number of people with the same vision join my project.

Please, create seperate issue here for every single idea and we'll discuss them. If you have code - create pull request. I haven't defined rules for pull request yet - just attach some description to your code.
Even if you have some ideas to architecture/layering/whatever - I'm open to disscussion.

P.S.: I need to update status of implementation and add some details. Now I'm finishing display/screen management in NXSystem and Preferences. So I was fighting bugs last couple of weeks and miss your issue.

**Comment by trunkmaster** [comment]
eukara, moved out of github.com. Closing issue.
