### ISSUE TITLE
Preferences bug: Brightness and Contrast

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#14]
Moving "Brightness" and "Contrast" sliders lead to application crash on real hardware. No crashes in virtual machine.

**Comment by armm77** [comment]
I have no problem of this type on my physical equipment.

**Comment by trunkmaster** [comment]
@armm77, what graphics card does your Xorg use?

**Comment by armm77** [comment]
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barts PRO [Radeon HD 6850]

X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System:  3.10.0-693.17.1.el7.x86_64 
Current Operating System: Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-693.21.1.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8
Build Date: 07 March 2018  01:39:22PM
Build ID: xorg-x11-server 1.19.3-11.el7_4.2 
Current version of pixman: 0.34.0

**Comment by trunkmaster** [comment]
You have no problem even if you're moving slider fast?

**Comment by armm77** [comment]
I have no problem, it works wonders.

**Comment by trunkmaster** [comment]
I've added XInitThreads() into -init method of Display Preferences' module. This fix for me crashes of Preferences with message:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
