### ISSUE TITLE
Screen settings

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#16]
It is possible to configure the screens and set the main and secondary screen, but when the session is closed the configuration is lost and the screens have to be reconfigured.

**Comment by trunkmaster** [comment]
@armm77, do you have files named like Displays-<some digits>.config at ~/Library/Preferences/.NextSpace?

**Comment by trunkmaster** [comment]
I've figured out where is the problem. I'll fix it soon.

**Comment by trunkmaster** [comment]
Fixed. Check it out.

**Comment by armm77** [comment]
Fixed this incidence. e2e39d5e1819ed81cba5ec5d0b8e3e144e284ec8
