### ISSUE TITLE
Dock icons

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#17]
I have a problem with the icons of the dock, those of the project are only displayed when I have the applications open, when closing they disappear, but the applications like firefox or Gorm (that compile) if they are viewed open or closed.

**Comment by trunkmaster** [comment]
Do you mean icons at bottom of the screen?

**Comment by trunkmaster** [comment]
Your WindowMaker configuration files are bad. Workspace use files located in ~/Library/Preferences/.WindowMaker (this path is set by Login via environment variable GNUSTEP_USER_ROOT). Replace it's contents with <NEXTSPACE github repo clone location>/System/etc/skel/Library/Preferences/.WindowMaker to return default settings from console (quit Workspace before replacing files).
BTW, do have any files inside ~/Library/WindowMaker/CachedPixmaps?

**Comment by armm77** [comment]
I close the incident because I have a hard drive failure, check in my laptop and it works correctly.
