### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by alexmyczko** [trunkmaster/nextspace#2]
It's really cool how you added the localisation thing into Preferences (with fall backs (by order)).
However you miss some languages. I had done something similar using wmaker menu integration:
http://www.aiei.ch/gnustep/gnustep-language/

You might want to add some more of the missing languages?

**Comment by trunkmaster** [comment]
I use languages defined in XKB (/usr/share/X11/xkb/rules/base.lst). Can you please check your distribution setup? What specific language do you miss in "Add Layout" panel (opened on "Add.." button click)?

**Comment by trunkmaster** [comment]
Oh I just realized what did you mean! I answered you about Keyboard layouts and you'va asked me about Localization! OK, the list of languages is constrained by languages supported by GNUstep libraries. And yes, I can add some extra languages and see how it works.

**Comment by trunkmaster** [comment]
Alex, I made some research in this area. Preferences' Localization section shows languages supported by GNUstep. So if you want to add some language to Preferences someone should add this language file to GNUstep first. Language file are located here '$(GNUSTEP_SYSTEM_LIBRARIES)/gnustep-base/Versions/1.24/Resources/Languages'. If you can create such files I can add them to gnustep-base.

**Comment by alexmyczko** [comment]
Such files already exist with gnustep base, i've got 1.25:
/usr/share/GNUstep/Libraries/gnustep-base/Versions/1.25/Resources/Languages# find .
.
./Dutch
./English
./Esperanto
./French
./German
./Hungarian
./Italian
./Korean
./Locale.aliases
./Locale.canonical
./Locale.encodings
./Russian
./Slovak
./Spanish
./TraditionalChinese
./Ukrainian

**Comment by alexmyczko** [comment]
I think I could contribute Swiss-German (we habe CHF and not EUR money) and I would like to have Polish...

**Comment by trunkmaster** [comment]
Fine! Send a pull request to GNUstep then. I have a plan upgrading to the latest GNUstep libraries after NEXTSPACE release.

**Comment by alexmyczko** [comment]
https://github.com/gnustep/libs-base/issues/28 almost, but Polish and Turkish is PRd

**Comment by trunkmaster** [comment]
I think this issue is GNUstep related. Closing this.
