### ISSUE TITLE
RPM: NextSpace Desktop 0.85

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#215]
Applications:
- Login
- Workspace
- Preferences
- TimeMon
- Terminal
- TextEdit

Frameworks:
- DesktopKit (former NXAppKit and NXFoundation)
- SystemKit (former NXSystem)
- SoundKit - NEW!

Tasks:
- [x] Workspace: fix focus problems while changing workspaces;
- [x] merge NXAppKit and NXFoundation into DesktopKit. Change class prefix to `NXT`;
- [x] rename NXSystem into SystemKit. Change class prefix to `OSE`;
- [x] SoundKit: change class prefix from `SKSound` into `SND`;
- [x] adopt new frameworks in applications;
- [x] TimeMon: fix color selection in preferences;
- [x] Sound Preferences: fix .gorm files;
- [x] create nextspace-frameworks and nextspace-applications RPMs;
- [x] do a clean install of CentOS and generated packages;
- [x] Plymouth theme set in -core package however font used by theme resides in -frameworks ;
- [x] split "Build and Install" wiki page into 2 "Install" for users and "Build" for developers (moved into issue #218 ).

**Comment by trunkmaster** [comment]
Revert commit `776c17dbf1dd09c955997ff742d095ca6144e228` - commit reduces flickering of appicon but introduces bad side effects. This should be inspected later during switch to `cairo` GNUstep backend.

**Comment by trunkmaster** [comment]
All tasks were completed. Hold RPM creation until #211 and #214 will be succeeded.

**Comment by zeroheure** [comment]
Can I start writing a press release about this release (in french) or do you prefer to keep NextSpace a bit "secret" until 1.0 ?

**Comment by trunkmaster** [comment]
@zeroheure, feel free to write a press release. I've wrote some notes here https://trunkmaster.github.io. You can use it as source of "what's new".

**Comment by trunkmaster** [comment]
I've just fixed Workspace .gorm files for renamed NXProgress* classes. I need to perform "Build and Install" guide testing.

**Comment by trunkmaster** [comment]
"Times New Roman" font was added to Plymouth theme.

**Comment by trunkmaster** [comment]
All tasks are done. Closing.
