### ISSUE TITLE
Change of size and movement of the windows more coherent to the appearance of OpenStep

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#217]
- [x] draw resize lines only for changed part of window - do not draw lines on visible window frame;
- [x] draw resize information on titlebar, replacing current window title while mouse is down.

**Comment by trunkmaster** [comment]
New "Titlebar" display style was added to Workspace/WM.

@armm77, what do you think? Any comments?
If you have already installed NEXTSPACE, set "ResizeDisplay" and "MoveDisplay" to "titlebar" in ~/Library/Preferences/.WindowMaker/WindowMaker after compile and install of fresh Workspace.

**Comment by armm77** [comment]
Yes @trunkmaster it meets the objective.

**Comment by trunkmaster** [comment]
Good. Closing PR #217.
