### ISSUE TITLE
CentOS keyboard setup ignored by NextSpace.

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#220]
It’s better to create new issue for keyboard setup. Keyboard setup made in CentOS ignored by NextSpace, right?

_Originally posted by @trunkmaster in https://github.com/trunkmaster/nextspace/issues/218#issuecomment-496502240_

**Comment by trunkmaster** [comment]
Fixed. @zeroheure, please confirm.

**Comment by trunkmaster** [comment]
No feedback for 18 days. Closing #218.

**Comment by zeroheure** [comment]
@trunkmaster I'm on holiday, wait a bit !

**Comment by trunkmaster** [comment]
OK, no problem.

**Comment by trunkmaster** [comment]
@zeroheure ?

**Comment by zeroheure** [comment]
I came back yesterday !
Give me a few days for urgent work before I test.

**Comment by trunkmaster** [comment]
You are still here. Good. ;) No problem, I'me waiting for your feedback.

**Comment by trunkmaster** [comment]
@zeroheure, any news?

**Comment by zeroheure** [comment]
on my way to reinstall and test
(I've by mistake deleted my Centos virtual machine)

**Comment by trunkmaster** [comment]
I hope to hear you soon...

**Comment by trunkmaster** [comment]
@zeroheure, I'm closing issue. You can reopen it if you'll notice some problems.

**Comment by zeroheure** [comment]
Wow, you finished Preferences ! Wonderful !

**Comment by trunkmaster** [comment]
> Wow, you finished Preferences ! Wonderful !
Why do you think so? I have not finished Prererences yet.

**Comment by zeroheure** [comment]
wnongly read the progress :(
