### ISSUE TITLE
I want original NeXT logo on the dock instead of centos logo. How do I change that?

### ISSUE THREAD

**Issue by rocheston** [trunkmaster/nextspace#222]
I want to replace the dock workspace logo to the original NeXT logo. Can you help, please?

I am impressed with your project. Good job.

**Comment by trunkmaster** [comment]
Replace /usr/NextSpace/Apps/Workspace.app/Resources/App-CentOS-48.tiff.

**Comment by trunkmaster** [comment]
@rocheston, may I consider issue resolved?

**Comment by rocheston** [comment]
Yes, it works. Trying to create a transparent TIFF. I want to remove the white background when using normal TIFF.

**Comment by trunkmaster** [comment]
I create it with GIMP.  File > New:
- "X resolution" and "Y resolution" = 72.00 pixels/in
- in Advanced Options set "Fill With" to "Transparency". 
After that export to TIFF. Should work.

**Comment by BertrandDekoninck** [comment]
PikoPixel.app is the perfect tool for this. Just select the background and erase it with the DEL key. Save it as TIFF.

**Comment by rocheston** [comment]
Thank you. Once again I love the NeXTSTEP look with your project. One small suggestion, The login window looks beautiful, nicely done but the localhost label ruins it. Thanks again.

**Comment by trunkmaster** [comment]
Show hostname on login panel is the original NeXT design. I'll think about making it optional (configurable).
