### ISSUE TITLE
Integrate SELinux support

### ISSUE THREAD

**Issue by fsmunoz** [trunkmaster/nextspace#228]
The documentation is absolutely clear on the need to disable SELinux and I assume this is because it is either non-trivial to work with it enabled or it is an additional complexity which was not a priority (likely both). That said:

* SELinux is enabled by default and it would mean one less change required during the installation process.
* In the future disabling SELinux could have other consequences in other parts of the system.
* Disabling it could be against security policies (e.g. corporate workstation policies) and thus not a practical option even when the users are technically allowed to change it.

It would be good if NEXTSPACE could work without changing the SELinux policy, and this issue is about suggesting that this is added as an item in the roadmap (likely in terms of System Integration), as well as sharing whatever initial information can be useful for anyone that wishes to help with that by e.g. using audit2allow to create a specific NEXTSPACE policy.

**Comment by trunkmaster** [comment]
Hi, @fsmunoz.

You are right at all your points. Basically, there are 2 reasons for disabling SELinux:
1. I'm not familiar with SELinux yet.
2. There's need to do extra changes to the system (create policy) because without it NEXTSPACE doesn't work.

Saying that, I mean I don't know how much effort need to be applied to make NEXTSPACE working with SELinux.
Do you want to inspect this area? Do you have some solution/idea?

I'm setting labels to this issue as 'enhancement' and `help wanted`.

**Comment by trunkmaster** [comment]
Hi @fsmunoz, sorry for the late reply. I need some time to check it. But, if I remember correctly it fails from the start - Login Panel doesn't start. If you have (or plan to) install NEXTSPACE, don't disable SELinux and check the logs.

**Comment by fsmunoz** [comment]
No worries, already on it and have installed and compiled it, was just looking for more context to be sure I don’t mistake regular build problems with SELinux related issues. Will give feedback here when I have something more.

**Comment by fsmunoz** [comment]
I've recently add both the time, resources and knowledge to analyse this in more detail, and it ends up being relatively simple in terms of the general approach, but with the associated complexity of SElinux policies.
The good news is that I have identified the necessary changes to make NEXTSTEP run with SELinux enabled:

![nextspace-selinux](https://user-images.githubusercontent.com/285727/88979666-0651de00-d2ba-11ea-971d-e1df75fa00b6.png)

Essentially I've found that there are 4 different components (thus far...) that need policies:

1. gdomap: this one is actually present in CentOS (all my tests were done in a CentOS 8 VM running on a RHEL 8 host) since usr/share/selinux/targeted/default/active/modules/100/gdomap exists, but looking at the policy file the problem is that that the paths are different (e.g. /usr/bin/gdomap is defined but NEXTSPACE uses /Library/bin/gdomap). Here I have essentially ajusted the .ts file and created a new ns-gdomap policy.
2. gdnc: I find it strange that I couldn't find more online information on this one and gpbs since GNUstep apps would also be affected by this... I couldn't find a ready-to-use policy so I created one based on setting SELinux to permissive mode mode and creating a policy file based on the registry.
3. gpbs: idem
4. Login: idem

It is not impossible that with more time and actions (e.g. some specific command like a restart that requires specific accesses that were not detected) more adjustments are necessary, but it's at least usable right now for anyone that can't disable SELinux. I think the solution here is to include the policy files and install them in the install script; I will work on packaging things better in the next days so I can propose a PR after getting your input on this.

**Comment by trunkmaster** [comment]
@fsmunoz great news! Waiting for PR...

**Comment by trunkmaster** [comment]
@fsmunoz I guess this issue could be closed since #327 was merged.

**Comment by fsmunoz** [comment]
@trunkmaster yes! I think that there will be quite a bit more work needed in general (especially once it starts getting used and problems become apparent) but in terms of this issue I think it's done: SELinux support is there.

**Comment by trunkmaster** [comment]
@fsmunoz thank you very much for your excellent contribution! Closing issue.
