### ISSUE TITLE
Untimely closure (Workspace).

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#23]
Steps to reproduce the event:
1). Minimize File Viewer.
2). Click on the File Viewer icon to restore it.

Note: to play in event, you should not have any other application open.

**Comment by trunkmaster** [comment]
Works correctly for me. What result did you observed?

**Comment by armm77** [comment]
I experience the same event in a vm (vmware fusion latest version) and in my laptop (hp 640 G2), the immediate closing of the Workspace and send me to the Login.

**Comment by trunkmaster** [comment]
Hmm... Works for me.

**Comment by trunkmaster** [comment]
@armm77, can you send me a gdb backtrace of Workspace?

**Comment by armm77** [comment]
apply your last change and the incidence was corrected, I think it is no longer necessary for you to send the gdb trace.

**Comment by trunkmaster** [comment]
Great! As you can see here https://github.com/trunkmaster/nextspace/projects/4 I'm working on tasks around focus issues. Be prepared to misbehaviour or crashes until I finish tasks.

**Comment by armm77** [comment]
Great, I'll help you perform the tests.
