### ISSUE TITLE
CentOS8

### ISSUE THREAD

**Issue by angwalu** [trunkmaster/nextspace#230]
Please could you help, I could not install nextspace on CentOS 8 I was following the install guide and didn't work. Can anybody help to install nextspace on CentOS 8?
 Davy

**Comment by trunkmaster** [comment]
@angwalu, Install Guide was written and packages were prepared for CentOS version 7. CentOS 8 is not tested yet.

**Comment by angwalu** [comment]
Hey Sergii

Is there any way you could develop Installer for the Nextspace, to make it
easier to install Nextspace.

Many thanks

Davy

**Comment by trunkmaster** [comment]
Davy, it can be an option for 1.0 release.

**Comment by angwalu** [comment]
That will be great Srgii, I am looking forward to it

Davy
