### ISSUE TITLE
Documentation: Build environment

### ISSUE THREAD

**Issue by DMJC** [trunkmaster/nextspace#233]
Hi, I'm attempting to build NextSpace on Debian. I've got multiple versions of clang/llvm available and the gnustep libraries and libdispatch installed. I am getting strange build errors regarding:

OSEScreen.m:471:29: error: array subscript is not an integer
      *redComponent = [dBack[@"Red"] floatValue];
                            ^~~~~~~
 and
OSEDisplay.m:253:11: error: use of undeclared identifier '_activeResolution'
          _activeResolution = [self resolutionWithWidth:mode_info.width
From what I can see these errors are compiler related and not to do with missing libraries. Can you update the build documentation with more detail about the objective-c runtime and compiler settings that should be used? I'd like to start packaging nextspace for Debian and potentially also contribute code back to the project. The direction this project is taking is in the same vein I was planning to go in with network/sound/video settings.

**Comment by trunkmaster** [comment]
@DMJC, show me output of the `make messages=yes` command, please.

**Comment by DMJC** [comment]
Making all for framework SystemKit...
clang OSEScreen.m -c \
      -MMD -MP -DGNUSTEP -DGNUSTEP_BASE_LIBRARY=1 -DGNU_GUI_LIBRARY=1 -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -fexceptions -fobjc-exceptions -D_NATIVE_OBJC_EXCEPTIONS -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -g -O2 -fgnu-runtime -W -Wall -Wno-import -Wno-unused -Wno-unused-parameter -pipe -DLINUX -DWITH_UDISKS -DWITH_UPOWER -fconstant-string-class=NSConstantString -I../ `pkg-config --cflags udisks2 dbus-1 upower-glib` -I/usr/include/gio-unix-2.0 -I./derived_src -I. -I/home/james/GNUstep/Library/Headers -I/usr/local/include/GNUstep -I/usr/include/GNUstep \
       -o obj/SystemKit.obj/OSEScreen.m.o

**Comment by DMJC** [comment]
I've fixed up the main problem which was the runtime being misconfigured. Thanks for the messages=yes statement, that made troubleshooting much easier. It looks like my main problem now is libdispatch. I will see if I can find a solution.

**Comment by nextspace411** [comment]
Hey, DMJC could you give me headup if you make it on Debian I would like it on Ubuntu too

Davy

**Comment by DMJC** [comment]
Looks like all you need is to select the objective-c 2 runtime and enable -fblocks in gnustep build environment, and install grand central dispatch and some dependancy libraries. If I'm right this should be simple to package for debian.

**Comment by DMJC** [comment]
NXTHelpPanel.m is missing an import for dispatch/dispatch.h which prevents compilation. Adding that fixes it. I can build all frameworks now.

**Comment by nextspace411** [comment]
Thanks DMJC I will try that on UBUNTU because if its work with Debian it wil works on Ubuntu too.
    On Friday, November 1, 2019, 11:04:17 a.m. PDT, DMJC <notifications@github.com> wrote:  
 
 
NXTHelpPanel.m is missing an import for dispatch/dispatch.h which prevents compilation. Adding that fixes it. I can build all frameworks now.

**Comment by trunkmaster** [comment]
Guys, read Build Guide carefully. The initial build error caused by lack libobjc2 library (Objective-C 2.0 runtime). The recommended build options for GNUstep libraries guarantees  <dispatch/ditspatch.h> include. This repo contains patches to GNUstep libraries of certain versions for the best NEXTSPACE usability result.

**Comment by doublet30** [comment]
I do have a suggestion, when the debian build is completed, keep a record of all dependencies installed for build, dependencies required for run time, and commands used for build.  Maybe we can get some automated CI/CD scripts setup to automate build during releases.  I am a developer for TTOS Linux (a debian derivative) and I would be willing to host a repository for Debian 10 and Debian Testing (future 11) compatible OS's (including Ubuntu).  As long as the Continuous Integration and Continuous Deployment is setup, you guys would have some free time to help contribute to projects such as these instead of constantly compiling them each time code is pushed.  At the moment, I have my plate full with some projects, but this is definitely one that caught my eye and out of nostalgia, I have considered brushing up on my objective C and contributing.  So... if anyone needs a volunteer to host a repository for Nextspace, contact me tomtravers@ttpc-systems.com and let me know.

**Comment by DMJC** [comment]
How important is the filesystem layout? E.g if I reuse the Debian filesystem layout for GNUstep will it break NextSpace? I'd like to stick to the Debian standards where possible for compatibility/ease of getting the packages merged into Debian itself.

**Comment by trunkmaster** [comment]
@DJMC, It should work with exception to some symlinks from /Library (Fonts, Images) to /usr/NextSpace. Check spec files to see what syminks are created during RPM install.

**Comment by alexmyczko** [comment]
are any of you on irc #gnustep ?

**Comment by alexmyczko** [comment]
@DMJC are you planning to join https://wiki.debian.org/DebianGNUstep/Team ?

**Comment by Letterus** [comment]
@doublet30 @DMJC @nextspace411 When building for Debian and Ubuntu please notice this repo where we set up build scripts that will lead to a working 2.0 runtime under Debian and Ubuntu: https://github.com/plaurent/gnustep-build/

Debian 9 is out of date now, but Debian 10 and Ubuntu schould work.

Regarding Ubuntu I already set up a team here: https://launchpad.net/~gnustep. Just waiting for help to come to reactivate https://launchpad.net/gnustep

CI builds here: https://travis-ci.com/plaurent/gnustep-build

**Comment by pgeorgi** [comment]
Note that Debian packaging support has been placed in https://github.com/trunkmaster/nextspace/tree/master/Packaging/Debian, with documentation and scripts to hopefully make it a painless experience. There are still open issues to resolve, but the overall scaffold is there. Patches accepted :-)

**Comment by Letterus** [comment]
> Note that Debian packaging support has been placed in https://github.com/trunkmaster/nextspace/tree/master/Packaging/Debian, with documentation and scripts to hopefully make it a painless experience. There are still open issues to resolve, but the overall scaffold is there. Patches accepted :-)

This is very great! Thank you! Looking forward to give it a try. Tagging @plaurent to let him know.

**Comment by angwalu** [comment]
Pgeorgi can someone make nextspace.iso on Ubuntu, I tried to install using Alien software it's didn't work nextspace-core could not work. I am not a developer so I was powerless if somebody can make .iso on Ubuntu I will appreciate that very much

**Comment by alexmyczko** [comment]
@pgeorgi did you see this:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962778

maybe you should maintain it for debian? thoughts?

**Comment by pgeorgi** [comment]
I've been through most of the process of becoming a debian developer a _long_ time ago and I have little interest to pursue that path again. My plan is to make this work, keep it working and hopefully empower debian based users and developers around nextspace to collaborate.

**Comment by alexmyczko** [comment]
Fair enough I will go ahead updating/maintaining that package I ITAd then

**Comment by trunkmaster** [comment]
As far as PRs from @pgeorgi were accepted I think this issue could be closed.

**Comment by Letterus** [comment]
Building (packages) for Debian is work in progress. But we reached the point where we could start Workspace as root. Further development can be observed as mentioned by @pgeorgi: https://github.com/trunkmaster/nextspace/issues/233#issuecomment-636288940
Thanks to @pgeorgi for his efforts!

**Comment by trunkmaster** [comment]
@Letterus I guess it would be more handy to change the title of the issue to "Debian packages" or create a separate issue for this. What do you think?

**Comment by Letterus** [comment]
@trunkmaster I think people now know where to find information to build under Debian. For further issues regarding Debian packaging we'd better open new tickets. So this one can be closed I think.
