### ISSUE TITLE
Dock messes up after crash

### ISSUE THREAD

**Issue by helgur** [trunkmaster/nextspace#238]
Installed this with CentOS 7 on a laptop. Unable to recover Nextspace desktop after it went into hibernation, so had to do a hard reset. After which all the icons on the dock where gone. 

Applaud your efforts with this. I am a big fan of clean, clutter less UI's and always liked the openstep look and feel. Excited to see what you make of the next release of Nextspace!:)

**Comment by trunkmaster** [comment]
This is Dock state file was zeroed. I've already think about it. You have 2 options right now:
1. Restore Dock contents by manually dragging applications to Dock. Then set autolaunch (Preferences->Dock) to those apps you want be automatically launched (Preferences, TimeMon).
2. Logout. In text console copy /etc/skel/Library/Preferences/.WindowMaker/WMState to ~/Library/Preferences/.WindowMaker.

I guess second option should be default. Mark this issue as bug.

**Comment by trunkmaster** [comment]
@helgur fixed in master branch. Can you test it?
 Thank you for report.

**Comment by trunkmaster** [comment]
@helgur ?

**Comment by helgur** [comment]
Sorry for the late reply, give me a couple of days to test this as I had to lend the laptop to a relative and haven't gotten it back yet, and I need to do a reinstall.

**Comment by trunkmaster** [comment]
OK, no problem.

**Comment by helgur** [comment]
Saved a backup image from my work laptop and installed centos 7 and nextspace on it. When successfully booting into nextspace and following the build prerequisite guide (https://github.com/trunkmaster/nextspace/wiki/Build-Guide) I am stuck with installing libdispatch (libdispatch-devel-1.3-1.el7.centos.x86_64.rpm from the list you provided at https://github.com/trunkmaster/nextspace/releases/tag/0.8):

"Feil: Package: libdispatch-devel-1.3-1.el7.centos.x86_64 (/libdispatch-devel-1.$
          Requires: libdispatch(x86-64) = 1.3-1.el7.centos
          Installert: libdispatch-1.3.1121-3.el7.x86_64 (@/libdispatch-1.3.1121$
              libdispatch(x86-64) = 1.3.1121-3.el7"

It seems the libdispatch-devel package you provided can't install because the libdispatch package provided at the same repository is outdated?

Also the root cause of this issue in the first place is centos 7 not being able to handle hibernation. I thought maybe upgrading the kernel might solve the issue (centos 7 uses linux kernel 3(!) so I upgraded to the latest kernel, but that didn't fix it apparently. On Debian/Ubuntu it manages hibernation just fine. (actually researching that issue in particular led me down quite the rabbit hole, see: https://unix.stackexchange.com/questions/308525/screen-stays-black-on-wakeup-from-suspend-centos-7). I am not really proficient at redhat, I switched to debian from redhat before the turn of the century, but dabbling with RPM's sure brought back some memories.

**Comment by trunkmaster** [comment]
> 
> 
> Saved a backup image from my work laptop and installed centos 7 and nextspace on it. When successfully booting into nextspace and following the build prerequisite guide (https://github.com/trunkmaster/nextspace/wiki/Build-Guide) I am stuck with installing libdispatch (libdispatch-devel-1.3-1.el7.centos.x86_64.rpm from the list you provided at https://github.com/trunkmaster/nextspace/releases/tag/0.8):
> 
> "Feil: Package: libdispatch-devel-1.3-1.el7.centos.x86_64 (/libdispatch-devel-1.$
> Requires: libdispatch(x86-64) = 1.3-1.el7.centos
> Installert: libdispatch-1.3.1121-3.el7.x86_64 (@/libdispatch-1.3.1121$
> libdispatch(x86-64) = 1.3.1121-3.el7"
> 
> It seems the libdispatch-devel package you provided can't install because the libdispatch package provided at the same repository is outdated?

It seems you've got confused with NEXTSPACE relases. You try install `libdispatch-dev` package from **0.8** release while you have installed `libdispatch` from **0.85** release. Please use dev and non-dev RPMs from the same release https://github.com/trunkmaster/nextspace/releases/tag/0.85.

> 
> Also the root cause of this issue in the first place is centos 7 not being able to handle hibernation. I thought maybe upgrading the kernel might solve the issue (centos 7 uses linux kernel 3(!) so I upgraded to the latest kernel, but that didn't fix it apparently. On Debian/Ubuntu it manages hibernation just fine. (actually researching that issue in particular led me down quite the rabbit hole, see: https://unix.stackexchange.com/questions/308525/screen-stays-black-on-wakeup-from-suspend-centos-7). I am not really proficient at redhat, I switched to debian from redhat before the turn of the century, but dabbling with RPM's sure brought back some memories.

Hm... It seems I need to think about moving to Ubuntu...

**Comment by helgur** [comment]
> It seems you've got confused with NEXTSPACE relases. You try install libdispatch-dev package from 0.8 release while you have installed libdispatch from 0.85 release

Oh, I thought those packages followed the same version as the latest release and thus I overlooked the version number. That is my bad.

> Hm... It seems I need to think about moving to Ubuntu...

If you do that I am pretty certain that nextspace will gain more interest (but that is maybe something you don't want at this stage). Nevertheless, speaking on behalf of myself, that would be awesome!

**Comment by trunkmaster** [comment]
@helgur what about issue topic? Did you test latest changes?

**Comment by trunkmaster** [comment]
@helgur ?

**Comment by helgur** [comment]
Right, having to work exclusively from home now due to the outbreak and I can't use CentOS on production as I risk loosing a lot of work if it hangs. Sorry. When I get time I'll do another reinstall and check back with you.

**Comment by trunkmaster** [comment]
@helgur any progress?

**Comment by trunkmaster** [comment]
Closing as fixed without feedback for a long time.
