### ISSUE TITLE
Trying to Install

### ISSUE THREAD

**Issue by liquidstatepro** [trunkmaster/nextspace#247]
Hello,

I am totally a noob here just messing around trying to install this on my CentOS8 Basic Install but I am unable to download the "X Window System". It says no group match for X Window System. Any ideas on how to proceed?

**Comment by armm77** [comment]
Hello @liquidstatepro , I suggest you do the installation as it appears on the wiki, because you will have other problems along the way with other libraries that are important to the project.

**Comment by enzuru** [comment]
@liquidstatepro for one thing, we only support CentOS7 right now.

**Comment by trunkmaster** [comment]
@liquidstatepro please try new 0.90 release: CenOS 7, CentOS 8, Fedora 31 packages were made available.

**Comment by trunkmaster** [comment]
@liquidstatepro ?

**Comment by trunkmaster** [comment]
Closing as fixed.
