### ISSUE TITLE
Can't be installed because of broken package

### ISSUE THREAD

**Issue by kbhors** [trunkmaster/nextspace#248]
Installing on a fresh centos according to instructions. All goes well until GNUStep libraries, when it falls over dead missing several lib*whatevers. see screenshot:
![gscreenshot_2020-04-06-163315](https://user-images.githubusercontent.com/29989061/78570891-dd4aa080-7825-11ea-8c0e-db91058f14a4.png)

**Comment by armm77** [comment]
Hi @kbhors, you can check the packages that you already installed before step 4, I think you are missing something. It is also important that you do the installation on Centos 7.

**Comment by kbhors** [comment]
I didn't miss a step, but this is centos 8. very dissapointing

**Comment by armm77** [comment]
Unfortunately you can not install the rpm is made for version Centos 7.

**Comment by kbhors** [comment]
and that's why RPM distros are dead

**Comment by trunkmaster** [comment]
@kbhors If you want to try NextSpace you have several options:
1. Follow each step of the "[Install Guide](https://github.com/trunkmaster/nextspace/wiki/Install-Guide)".
2. Try live ISO image (discussed here https://github.com/trunkmaster/nextspace/issues/242).
2. Help to create packages for CentOS 8 and share your specs with community.
3. Help to create packages for non-RPM distros and share created files with community.

You've definitely missed the step 1 from "Install Guide" and try to install packages on wrong OS version. I consider this issue as invalid.

**Comment by kbhors** [comment]
it was reasonable to expect the existing packages to just work. them breaking on the current OS release is the sort of absurdity linux was supposed to have left behind back in the 2000s. athough maybe i shouldn't be surprised, centos feels like bad old days linux of incoherent documentation and elitist men with ugly beards. you're building a mansion on a crumbling cliff

**Comment by trunkmaster** [comment]
> it was reasonable to expect the existing packages to just work. 

Every application has a system requirements. Existing packages were made for CentOS 7 and this clearly stated in documentation.

> them breaking on the current OS release is the sort of absurdity linux was supposed to have left behind back in the 2000s. athough maybe i shouldn't be surprised, centos feels like bad old days linux of incoherent documentation and elitist men with ugly beards. you're building a mansion on a crumbling cliff

Of course, you are right. ;) Where can I test your packages?

**Comment by kbhors** [comment]
CentOS 7 as a system requirement doesn't (and shouldn't) mean CentOS 8 breaks it. I have dozens of boxes of software here says requires windows 95, but works on windows 98 or XP, dozens that says Amiga500, works on 4000, some saying Mac System 7, works on Mac OS 9... Entirely reasonable to be disapointed when the 50 year old OS family fails this simple thing that the "lesser" systems can do.

What will you do when CentOS 7 is too old? Move to CentOS8 until that is too old too? What does CentOS 7 offer in particular? Must be something special if other linux doesn't have it.

**Comment by alexmyczko** [comment]
What often works is you take the source code and build it yourself.

**Comment by uchuugaka** [comment]
This kind of complaining isn't really helpful.
Put in the effort to help make something portable on versions of an OS or to other OS's.
Compatibility takes time to bake in to a build system.
First thing is to get it off the ground.
CentOS btw is all about long lived stability. It frequently has relatively ancient software bundled in it, but the reason it is well-loved among infrastructure folks is that it is not a moving target of software configuration hell.
