### ISSUE TITLE
Battery dock icon for laptops

### ISSUE THREAD

**Issue by enzuru** [trunkmaster/nextspace#252]
I'm developing on a NEXTSPACE laptop right now, and it's fantastic. The primary thing that is problematic is the lack of battery dock icon.

I'm more than happy to do this work myself after the Emacs and Ansible work I already committed to. I am just submitting an issue so we can catalogue it and discuss it.

**Comment by armm77** [comment]
Hi @enzuru , I think this [BatMon](https://github.com/hezi/BatMon.app) could help you.

**Comment by trunkmaster** [comment]
@enzuru Great to know somebody use NEXTSPACE. I expect more submitted bug reports/issues. ;-)

I have plan to add power preferences (as well as battery status). Look here https://github.com/trunkmaster/nextspace/projects/2. I think it should be implemented with UPower via DBus. It's more then just display of battery status - it should be a subsystem with ability to send a notifications to applications. Applications should observe these notifications and be prepared for power off/shutdown events, for example.

I'm busy with network preferences implementation now using DBusKit and NetworkManager. Actually it's a seperate application right now (Applications/Network) and its implementation is in intial state.

**Comment by enzuru** [comment]
Ah. Given that there is already a third party alternative, and that power preferences are on the road map, I will close this request. Thank you.
