### ISSUE TITLE
Building for Newer Hardware

### ISSUE THREAD

**Issue by uchuugaka** [trunkmaster/nextspace#253]
Problem Statement

It is increasingly difficult to run CentOS 7 on new hardware. 
Running inside a VM is an option but also not a true experience. 
It would be great to find out what is required to get NextSPACE for newer hardware. Presumably either CentOS 8 or the rolling distro or one of the Fedora trains. 

Presumably an installer would be part of that as well.

**Comment by trunkmaster** [comment]
@uchuugaka I understand the problem. The most simple way is to modify existing .spec files to build on Fedora and CentOS 8.

Mark this as feature request for now.

**Comment by armm77** [comment]
Hi @uchuugaka, after spending several days fighting with Centos 8, I managed to make NEXTSPACE work, but before sharing the process I want to try it with fedora, since @trunkmaster  plans to migrate to that version and to focus on more important issues.

![Screen Shot 2020-04-23 at 11 38 31 PM](https://user-images.githubusercontent.com/3104815/80210564-94526480-85f9-11ea-93b4-c786b9f7c1d4.png)

**Comment by uchuugaka** [comment]
Awesome. To be honest, Fedora is a more attractive option !!
Looking forward to that!
Good timing with a new major version coming soon. 

Beyond Fedora, a FreeBSD would also be amazing. 

>

**Comment by enzuru** [comment]
I am a big BSD fan (especially OpenBSD) and think that the BSD community might appreciate this project even more than the Linux community, as they are less in love by shiny new desktops.

**Comment by enzuru** [comment]
Also... if we're switching to Fedora soon, I am going to hold off on writing Ansible scripts for CentOS 7.

**Comment by streaps** [comment]
> Awesome. To be honest, Fedora is a more attractive option !!

Debian is the more attractive option ;).

**Comment by trunkmaster** [comment]
@enzuru CentOS 7 will be a base OS for some time. I have no plans to drop NEXTSPACE developement and switch to make "ports". I will gladly support someone's decision to adopt .spec files to other Linux distributions. 

*BSD is something different. Several years ago I've started my development on FreeBSD, but dropped it in favour of more functional and actively developed Linux technologies (DBus, UDisks, UPower, PulseAudio etc).

**Comment by enzuru** [comment]
Understood @trunkmaster. I think for now avoiding BSD and other Linux platforms makes sense unless someone wants to volunteer to step up and support them.

**Comment by nicktelindert** [comment]
Fedora would be a great idea, i see @armm77 already has fedora 31 specs in his repository. I definitely could use those to create a ready to install Fedora iso. But i wait for 1.0 first.

**Comment by armm77** [comment]
Hi @nicktelindert , I stopped my work because @trunkmaster confirmed that he would update the project spec, it is better to wait for the update to finish, so that you can continue with your work.

**Comment by trunkmaster** [comment]
@nicktelindert, @armm77 I've already updated specs to build packages for CentOS 7, CentOS 8, Fedora 31. Also I've created a build scripts (in `scripts` subdirectory) to automate build sequence.

Frankly speaking I've built packages for all mentioned distributions and I plan to make them public along with 0.90 release.

**Comment by nicktelindert** [comment]
@trunkmaster Great to hear that. Than i add some iso building scripts for fedora 31 and centos 8 as soon as those packages are public. I probably dont have to change anything except for the nextspace packages and add the correct docker environment.

**Comment by uchuugaka** [comment]
Does that mean we might soon see Fedora 31 and CentOS 8 ISOs? That’s going to garner attention for sure.

**Comment by nicktelindert** [comment]
@uchuugaka If the packages are publicly available for those distros then i will at least create the iso generation script. A ready-to-download iso for 1.0. I made generating an iso as easy as possible so pretty much any one can do it.

**Comment by uchuugaka** [comment]
That’s just wonderful. I look forward to giving it a go.

**Comment by trunkmaster** [comment]
@nicktelindert I'm preparing to upload packages to GitHub. Since I have to upload RPMs for 3 distributions and I feel it would be a mess if I upload a lot of packages as one list. 

Also I want to seprate packes for users (normal RPMs) and developers (-devel and -debuginfo RPMs).

Now I see 2 viable options:
1. Make 2 (NSUser and NSDeveloper) files for each distribution with RPMs and possibly install script inside each as single release.
2. Create 3 separate releases (one for each distribution) with published RPMs and NSUser.tar.gz and NSDeveloper.tar.gz

What is the preferable option for ISO building? Other ideas?

**Comment by trunkmaster** [comment]
@uchuugaka please try new 0.90 release: CenOS 7, CentOS 8, Fedora 31 packages were made available.

**Comment by nicktelindert** [comment]
@trunkmaster Will this be the new way for distribution nextspace? I see you now use a shell script and archives to install nextspace.  I will fix my build script sometime this week. I'll try to add Centos 8 and Fedora 31 too.

**Comment by trunkmaster** [comment]
@nicktelindert please see my post above. IMHO this is the fastest method to make 1 release on github. Do you have other ideas (for instance, site where we can place RPM repository)?

**Comment by nicktelindert** [comment]
@trunkmaster 
Sorry i had not seen your previous message. I think in the future the best thing to do will be a repository. That way you would have an upgrade path. And you add the repository to the iso and always install the latest version available.  I do have a server which can be used to host the repository.  Have to look into that, i now only host 1 site, but when i most multiple stuff i'd rather have them in separate containers for security reasons.

**Comment by trunkmaster** [comment]
@nicktelindert it's fantastic! I wish we'd have YUM repo site. Drop me a note if you'll need help to setup repo.

**Comment by nicktelindert** [comment]
@trunkmaster 
I already did some preparations and moved to docker for my current website. Because i am lazy i now have everything scripted to make it very easy to add a new domain. I will start working on the repository itself this Saturday.

**Comment by nicktelindert** [comment]
@trunkmaster We do need a domain though, otherwise we would have an url like repo.ledzeppelincoverband.nl. That is a little confusing i think:P. I understand you probably want to claim a domainname yourself. So maybe you can look into that?

**Comment by zeroheure** [comment]
@trunkmaster @nicktelindert We can build packages on SuSE Open Buil Service, then OBS will provide repositories. It will save bandwith. 

I can provide a server too, in France. With two servers, we will get an international hosting ! :-)

**Comment by nicktelindert** [comment]
@zeroheure That sounds like a great idea, i look into that.

**Comment by trunkmaster** [comment]
> 
> 
> @trunkmaster We do need a domain though, otherwise we would have an url like repo.ledzeppelincoverband.nl. That is a little confusing i think:P. I understand you probably want to claim a domainname yourself. So maybe you can look into that?

We can start with generic domain. It is not user visible and can be added to user's system with nextspace.repo files.

**Comment by trunkmaster** [comment]
> 
> 
> @trunkmaster @nicktelindert We can build packages on SuSE Open Build Service, then OBS will provide repositories. It will save bandwith.
> 
> I can provide a server too, in France. With two servers, we will get an international hosting ! :-)

Excelent. It would be great if someone could setup OBS. You can find build instructions inside Packaging/RedHat subdirectory.

**Comment by zeroheure** [comment]
@trunkmaster I think @nicktelindert already started that. I don't have much spare time, but may be I can help if nicktelindert share his OBS access.

**Comment by zeroheure** [comment]
I've started an OBS project at https://build.opensuse.org/project/show/home:zeroheure It is open, if one wants to help.
It is a the very beginning : trying, testing, learning.
Curently I try to provide needed Centos Software repositories and packages. I'm testing various solutions because some of them are not curently available in OBS.

**Comment by nicktelindert** [comment]
@zeroheure I already pretty much have a working obs environment.  I just need  just have 1 thing to fix and it is good to go.
https://build.opensuse.org/project/show/home:nick.lindert. Centos 7 already succeeds building but somehow it is missing block.h. I hope to get working on it this weekend. I just have centos 7 turned on, if that works i turn centos 8 on. But there wouldn't be much difference in getting it to work. I invite to to collaborate further on my obs so we don't waste resources.

**Comment by nicktelindert** [comment]
@zeroheure You are added as one of the maintainer

**Comment by zeroheure** [comment]
Thanks ! It's much better to share effort.

**Comment by zeroheure** [comment]
@uchuugaka [CentosPlus repository](https://wiki.centos.org/AdditionalResources/Repositories/CentOSPlus) provide more hardware support, but need to be enabled.

**Comment by trunkmaster** [comment]
@uchuugaka can close this issue as fixed?

**Comment by uchuugaka** [comment]
Yes!
