### ISSUE TITLE
Determine correct location of TimeMon.app

### ISSUE THREAD

**Issue by pgeorgi** [trunkmaster/nextspace#270]
The WMState config looks for /Applications/TimeMon.app/TimeMon while the config as used by the debian package installs it to /usr/NextSpace/Apps/TimeMon.app/...

Once I know where it should reside, I can fix up the part that is incorrect. Are there docs describing where parts should end up?

**Comment by trunkmaster** [comment]
Unfortunately, I have not wrote doc for filesystem hierarchy. The basic idea: put all stuff that shouldn't be visible to the user into /usr/NextSpace. Otherwise /Applications, /Library, /Developer is a right locations.

**Comment by pgeorgi** [comment]
Thanks for the explanation. To fill this out with some example:
I guess Workspace and Login aren't supposed to be user-visible (because they're started by the system and remain persistent: there's little reason for users to interact with the binaries). TextEdit is user visible.

Back to the issue at hand: What about TimeMon?

**Comment by alexmyczko** [comment]
I would suggest to keep it consistent and not separate. Users might want to load stuff with Gorm and make translations (localization). If it is Gorm based...

**Comment by trunkmaster** [comment]
@pgeorgi TimeMon as well as Preferences can be detached from the Dock and not start after login. It should be possible to drag application to Dock from File Viewer or launch application. 
Moreover TimeMon may be replaced with some other monitoring application and even deleted. I guess the answer is obvious.

**Comment by trunkmaster** [comment]
@alexmyczko I suppose you mean special user - developer. This type of user should be familiar with environment concepts and go directly to the Workspace app bundle with Workspace's Finder.
