### ISSUE TITLE
[0.90] Lock directory in Preferences prevent new account to run

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#276]
Newly created users can't do anything before directory `/Users/[New User]/Library/Preferences/.lck/` is removed from tty. 

Actualy GUI is like frozen. One need to open a tty, remove the `.lck` directory and restart NextSpace.

That directory is not in /etc/skel/Library/Preferences/ but comes from the first run. It doesn't come back after removing.

Packages : Centos 7

**Comment by trunkmaster** [comment]
@zeroheure did you reboot system after `nextspace_install.sh` run? I suspect SELinux.

**Comment by zeroheure** [comment]
Well, I wasn't totaly sure of that, so I did a clean new install, with reboot, and got exactly the same behaviour.

Each new user got the problem.

**Comment by zeroheure** [comment]
I've forgoted a few things :

- Workspace Menu and File Viewer doesn't launch
- top icon (Cents in mycase) is grayed
- after `.lck` removing, system shutdown is very slow.

**Comment by trunkmaster** [comment]
@zeroheure I've found the cause of a problem: there's no user directories /tmp/GNUstepSecure and ~/Library/Services so GNUstep services won't start. This not a specific problem to NEXTSPACE. This is an issue for any GNUstep based app. I'll see what I can do.

**Comment by trunkmaster** [comment]
@zeroheure latest commit to Applications/Login fixes this issue. Check out please.

**Comment by zeroheure** [comment]
I confirm the fix. Closing.
