### ISSUE TITLE
[0.90] Missing xorg graphic drivers

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#277]
This is a dependency problem : NextSpace 0.90 install script miss a dependency upon xorg graphical drivers (xorg-x11-drivers). Running it on real hardware, let X11 crash on startup.

There are also other useful packages missing but X can run without them (xinit, ...). Running `yum groupinstall "X Window system"` install all needed packages.

Harware was Dell inspiron 1501 with Centos 7 minimal install.

**Comment by trunkmaster** [comment]
@zeroheure I think adding `xorg-x11-drivers` dependency would be enough in this case. What other useful packages do you miss?

**Comment by zeroheure** [comment]
I will do a complete and carefull reinstall, annotating step by step to be sure of what happened.

Adding a step in install script like "Are you installing on real hardware ?" can simply help.

> I try to keep minimal footprint for NEXTSPACE 

And the resul is fabulous ! only 280 MB of Ram in use, Whoohoo !

**Comment by zeroheure** [comment]
resolved by #280
