### ISSUE TITLE
[0.90] Plymouth doesn't exit

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#278]
See #277 for related problems.
With X crashing on startup, Plymouth doesn't exit while network is unavailable. System is totaly unusable and must be unplugged. I don't know if it is a known Centos 7 bug.

While installing Centos, one can easily forget to activate network at boot time (the installer doesn't activate it for you). The NextSpace install script should check and activate it if needed.

**Comment by trunkmaster** [comment]
> See #277 for related problems.
> With X crashing on startup, Plymouth doesn't exit while network is unavailable. System is totaly unusable and must be unplugged. I don't know if it is a known Centos 7 bug.

Have you able switch virtual terminal (Ctrl+Alt+F2)? Xorg starts on first virtual terminal (vt0, Ctrl+Alt+F1).

> While installing Centos, one can easily forget to activate network at boot time (the installer doesn't activate it for you). The NextSpace install script should check and activate it if needed.

nextspace_install.sh is not aimed to completely configure CentOS. It is automated install of NEXTSPACE packages and some slight configuration that is not covered by CentOS install process (SELinux, /etc/hosts, EPEL repository).

**Comment by zeroheure** [comment]
Virtual terminal are not available until Plymouth exit.
Without NextSpace Plymouth exit gracefully. 

I will try a complete and carefull reinstall, annotating step by step to be sure of what hapenned.

**Comment by trunkmaster** [comment]
This is not network related problem. This is the Login application issue - Login application controls stop of Plymouth. If it's crashed Plymouth continue to run. I need to check and fix Login startup code to prevent it from happening.

**Comment by trunkmaster** [comment]
@zeroheure fixed in master. Check it please.

**Comment by trunkmaster** [comment]
@zeroheure may I consider this issue fixed?

**Comment by zeroheure** [comment]
Sorry, I totaly forgot to report. Yes it works now (fully tested).
