### ISSUE TITLE
[0.90] Centos7 boot with Centos plymouth screen instead of NextSpace one

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#279]
This happened after minimal Centos7 install on real hardware, immediatly followed by NextSpace install. No updates were done before NextSpace install script launched.

Centos ends up with two kernel options in Grub, let's call them the old and the new.
The old boot with NextSpace lovely plymouth screen but the new still boot with the default Centos plymouth screen.

See #277 for related problems.

**Comment by trunkmaster** [comment]
I guess plymouth update resets default theme and initrd updated while kernel update installed after that.

**Comment by zeroheure** [comment]
I've done the complete and documented reinstall mentioned in other reports. Now there is no Plymouth boot screen anymore (neither Centos or NextSpace).


NextSpace 0.90 on a QEMU/KVM virtual machine through libvirt
### install Centos 7 minimal, 
- french localization, keyboard variant is fr-bepo
- create user xavier (sudo ability)
- yum update
- yum install epel-release
- yum update
- yum install nano, mc (Midnight Commander)
### clone Centos7 VM
- yum update
- reboot (if kernel update)
### NextSpace install
- login as xavier
- mount USB key
- copy NextSpace tarball
- umount USB key
- tar zxvf NextSpace-0.90-Centos_7.tgz
- sudo NextSpace-0.90/nextspace_install.sh
    - answer y to all questions
    - create user zaza, low secure passwd
    - script doesn't offer to start login panel
- reboot
    - **no plymouth at all**
    - **checked on every available kernel**
- login (issue #276)
- reboot, then force reboot
- fix known issue #276
- graphical login with zaza

**Comment by trunkmaster** [comment]
@zeroheure thank you for details. I've made almost the same steps (VirtualBox, localization - English, user: nsinstall, download .tgz file from github) - success. Try to run command `plymouth-set-default-theme` without parameters after running `sudo ./nextspace_install.sh` (notice: if you'll run `sudo NextSpace-0.90/nextspace_install.sh` NextSpace will not be installed). It should return `nextspace`. If yes, then it's a problem of VM video driver.

Also try to redownload release .tgz file form github. I guess I've included fix for #276 into new release tarball.

**Comment by trunkmaster** [comment]
@zeroheure any news regarding this issue?

**Comment by zeroheure** [comment]
I will test again before the end of august.

**Comment by zeroheure** [comment]
Not done yet. I am very sorry.

**Comment by zeroheure** [comment]
on which NS version do you want me to test ?

**Comment by trunkmaster** [comment]
Hi @zeroheure, closing issues. Feel free to reopen it when you'll have possibility to make testing.
