### ISSUE TITLE
[0.90] menu not updated when application is shaded

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#282]
There is a strange behaviour with app menus when some windows are shaded.
## Simple case on VM (vesa driver)
Shade File Viewer window then open Terminal. The Terminal menu is drawn above Workspace menu.
You can play with various window shade/unshade, menus are a total mess.

## Real hardware (radeon driver)
Open Teminal and TextEdit document. Play with both windows by shading/unshading. Quickly apps menus will not update anymore.

**Comment by trunkmaster** [comment]
Confirmed.

**Comment by trunkmaster** [comment]
@zeroheure fixed in master. 

Although I'm not happy with focus management yet. Changing focus with titlebar clicking, make application main menu focused (wrong GNUstep focus handling).

**Comment by trunkmaster** [comment]
@zeroheure sorry, not fixed yet.

**Comment by trunkmaster** [comment]
@zeroheure I guess now it's fixed now. Fix needs changed GNUstep Back (located in Libraries/gnustep/tests/back-art). You need to build and install this version manually. Now I need to document current focus and application management until I forget details.

**Comment by zeroheure** [comment]
Wow, thanks !

**Comment by trunkmaster** [comment]
@zeroheure should I consider this problem resolved and close this issue?

**Comment by zeroheure** [comment]
Sorry I'm a bit in holidays and very busy working on an ERP migration. Strange holidays. Please wait.

**Comment by trunkmaster** [comment]
No problem. Also please take a look at other fixed issues reported by you.

**Comment by trunkmaster** [comment]
Closing as fixed.
