### ISSUE TITLE
[0.90] language indicator on Centos icon is not updated

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#284]
This is a minor bug, it doesn't affect keyboard nor Centos language settings. 
I've setup Centos with french language setting and keyboard. But language indicator on the dock (on Centos icon) is allways set on `us`.

**Comment by trunkmaster** [comment]
@zeroheure show me your `localectl` output.

**Comment by trunkmaster** [comment]
@zeroheure fixed in master. Checkout please.

**Comment by trunkmaster** [comment]
@zeroheure ?

**Comment by trunkmaster** [comment]
Closing as fixed.
