### ISSUE TITLE
[0.90] Localization preferences has no effect

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#285]
I've setup Centos with french language and keyboard. 
At first boot, Preferences.app Localization section shows right settings (like € symbol in currency). But after playing with it it allways show US settings for currency and others are not updated. 
A funny little bug might be related : in Date and Time, seconds increase or decrease when cliking on language.

**Comment by trunkmaster** [comment]
@zeroheure please be more specific. What do mean "playing with it" exactly? Could you please provide me scenario that I can reproduce?

**Comment by zeroheure** [comment]
Here's my general install process :

    use of QEMU/KVM through libvirt
    install Centos 7 minimal, french localization, keyboard variant is fr-bepo
    yum update
    yum install epel-release
    yum update
    yum install nano
    copy NextSpace tarball
    setup NextSpace with nextspace_install.sh
    start login panel with nextspace_install.sh last step
    login with user created by nextspace_install.sh
    logout
    fix known issues #276
    reboot

Now for Localization in Preferences.app :

1. Open Preferences.app
1. Localization/Numbers & Currency shows "€" symbol
1. click on any of the Language listed in Localization
1. Localization/Numbers & Currency shows "$" symbol

Date & time case

1. time dosn't updates in Localization/Date & Time (i.e. seconds/minutes stay the same)
1. try several clicks on  any of the Language listed in Localization
1. see seconds increasing in Localization/Date & Time

**Comment by zeroheure** [comment]
Here's test report conducted on a new Centos 7 VM.

### At first opening, Localization Preferences shows a mix between french and US locales
1. Language
    nothing selected
1. Date & Time
    Dimanche 28 Juin 2020
    28/06/2020
    16:05:16
    Dim 28 Jun 16:05:16 +0300 2020
    28 Jun 16:05
1. Numbers & Currency
    EUR9,999.00
1. Text Encoding
    Unicode
1. Measurement Units
    Centimeters

Note that there is some translations and format errors. Does it comes from Centos or are you using your own i18n files ?


### Select "Français" in languaqe
1. Language
    nothing selected
1. Date & Time
    Sunday, june 28, 2020
    06/28/2020
    16:05:16
    Sun Jun 28 16:05:16 +0300 2020
    28 Jun, 2020 16:05
1. Numbers & Currency
    $9,999.00

Everything is now set with US locales.

**Comment by trunkmaster** [comment]
> 
> 
> Here's test report conducted on a new Centos 7 VM.
> ### At first opening, Localization Preferences shows a mix between french and US locales
> 
>     1. Language
>        nothing selected
> 
This list is not selectable. This list represents the languages order.
>
>     2. Date & Time
>        Dimanche 28 Juin 2020
>        28/06/2020
>        16:05:16
>        Dim 28 Jun 16:05:16 +0300 2020
>        28 Jun 16:05
> 
>     3. Numbers & Currency
>        EUR9,999.00
> 
>     4. Text Encoding
>        Unicode
> 
>     5. Measurement Units
>        Centimeters
> 
> 
> Note that there is some translations and format errors. Does it comes from Centos or are you using your own i18n files ?
>
It comes from GNUstep.
>
> ### Select "Français" in languaqe
>
What do you mean by "select"?
>
>     1. Language
>        nothing selected
> 
>     2. Date & Time
>        Sunday, june 28, 2020
>        06/28/2020
>        16:05:16
>        Sun Jun 28 16:05:16 +0300 2020
>        28 Jun, 2020 16:05
> 
>     3. Numbers & Currency
>        $9,999.00
> 
> 
> Everything is now set with US locales.

**Comment by trunkmaster** [comment]
@zeroheure is it still an issue?

**Comment by zeroheure** [comment]
I didn't tested for a long time. 
I will try to reinstall before the end of august.

**Comment by trunkmaster** [comment]
OK. Please read carefully my last post with comments. I want to know if you understand key consepts behind Localization Preferences panel.

**Comment by zeroheure** [comment]
Hi @trunkmaster  I am very sorry, I can't do any testing before january.

**Comment by trunkmaster** [comment]
Hi @zeroheure, closing issues. Feel free to reopen it when you'll have possibility to make testing.
