### ISSUE TITLE
[0.90] Shell history is not recorded

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#286]
Title says all. Each time one close the Terminal window, the shell history is lost. There is no `.history` file.

**Comment by trunkmaster** [comment]
Confirmed. zsh configuration file named `.zshrc.nextspace` in `/etc/skel`. This file needs to be renamed to `.zshrc` on first user login.

**Comment by trunkmaster** [comment]
Fixed in master. Please use latest version of `System/etc/profile.d/nextspace.sh`.

**Comment by trunkmaster** [comment]
Closing as fixed.
