### ISSUE TITLE
Useful user oriented applications to install

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#287]
Everyone wanted to try NextSpace must install Centos or Fedora. Some users will be totaly new to Centos or Fedora and will need some help to install necessary day-to-day applications. Before writing instructions or creating a helper package, I want to note some ideas.

For consistency, we don't want to install a lot of libraries. After a few searches, it looks like there is more gtk2/gtk3 applications available on Centos 7, but Qt is more common on lighter tools. A few GNUStep apps can be packaged. I use [pkgs.org](https://pkgs.org/) to find what is available on Centos 7, 8 and Fedora 31. ~STRIKE~ items denote something unavailable.

# New end users will need (minimal)
- a graphical package management : yumex (gtk2)
- list of repositories (might be already enabled by package helper)
- a light browser : ~Midori~, Otter-browser (Qt5), ~Qupzilla/Falkon~, ~Epiphany~
- Firefox or Chromium
- light office suite : Calligra, ~Abiword~ (not C8), ~Gnumeric~ (not C8)
- LibreOffice, OnlyOffice
- a PDF reader : GSPdf.app (to package), ~muPDF~ (not C8), ~xpdf~ (not C8)
- a calculator : EdenMath.app (to package)
- may be an email reader ? GNUmail.app (to package)
- a sound player and video viewer : VLC can read quite everything, Mplayer.app (to package)

**Comment by zeroheure** [comment]
The [dooble](https://github.com/textbrowser/dooble) browser has no dependencies (but Qt5). It is actively developped, but unpackaged for Centos/Fedora.

**Comment by trunkmaster** [comment]
@zeroheure I think this information has no relation to the NEXTSPACE project. Please host it inside your project.

**Comment by zeroheure** [comment]
@trunkmaster Yes, there is no direct relation with NextSpace. But I think this information can go to the wiki, because Centos is not the usual desktop for many people (and NextSpace is a desktop !). 
Even using Centos on servers don't help to find good packages to install on desktop because you don't use same repositories, you don't often change the server setup (me : never), you don't read the same docs, etc.

**Comment by armm77** [comment]
I think that this entry should be moved towards this project.
https://github.com/nicktelindert/nextspace-build-iso

**Comment by trunkmaster** [comment]
Closing this as invalid issue.
