### ISSUE TITLE
Attempt to port to Arch.

### ISSUE THREAD

**Issue by daemonspudguy** [trunkmaster/nextspace#290]
Even an Arch port would make this far more appealing to use.

**Comment by zeroheure** [comment]
This is already explained in the README and there is several reports about porting work done on other linux distros: 

- first step is to make it working well on Centos 7
- 0.90 is available on Centos 8 and Fedora
- it works on Debian
- 0.90 packages are coming for Debian

If you want it on Arch, please compile, try to install and document steps.

**Comment by rcarmo** [comment]
Good to know it’s working on Debian, since it would make a killer environment for the Raspberry Pi.

**Comment by streaps** [comment]
> it would make a killer environment for the Raspberry Pi.

How much RAM does a basic installation use?

**Comment by zeroheure** [comment]
@streaps around 300 MB

**Comment by trunkmaster** [comment]
@daemonspudguy it's an Open Source project. Feel free to make a commitment in the form of documentation, scripts or package build files. NextSpace already has files to build packages for Debian.

**Comment by daemonspudguy** [comment]
@trunkmaster I have just installed it on my Chromebook and will see what I can find. I'm still new to the GNUStep world so any pointers would be most appreciated!

**Comment by daemonspudguy** [comment]
through CentOS, in case you were wondering

**Comment by zeroheure** [comment]
@daemonspudguy Currently, there is no packaged GNUStep applications for Centos (you car seach for that on pkgs.org). I am slowly working on this. You can help if you want.

**Comment by daemonspudguy** [comment]
I'll try to see what I can find. :)

**Comment by trunkmaster** [comment]
@daemonspudguy great news! 

Although do not expect to see all available GNUstep applications on top of NEXTSPACE: I'm very picky about application design (I mean "design" in a wide sense - not only visual side of it). But I wish to see more applications aligned with NEXTSPACE in the future. ;)

**Comment by daemonspudguy** [comment]
I've already repackaged certain GNUSTEP components on the aur. I am currently working to repackage Terminal.app as it was broken.

**Comment by zeroheure** [comment]
@daemonspudguy would you mind join us on Suse Open Build Service ? 

OpenBuildService can build packages for Arch, Debian, Ubuntu, SuSE, Mageia, Fedora, RedHat and Centos. And provide downloadle and signed packages repository.

We will be able to share solutions, may be one « universal » packaging recipe, and re-package GNUStep Apps. Fred Kiefer (from GNUStep) already build Fedora and SuSE GNUStep packages on OBS.

**Comment by daemonspudguy** [comment]
Sure. I'll join you. I'm daemonspudguy on the site.

**Comment by zeroheure** [comment]
@daemonspudguy I've added you as a maintainer in OBS home:nick.lindert repository. 
I am working in a branch (home:zeroheure:branches:home:nick.lindert) on Centos / Fedora packages.

**Comment by trunkmaster** [comment]
@daemonspudguy I think this issue can be closed since all related activity was moved into OBS.

**Comment by daemonspudguy** [comment]
@trunkmaster Okay.
