### ISSUE TITLE
ProjectCenter does not compile projects

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#291]
While compiling a project, the make complains about:
GNUSTEP_USER_ROOT is obsolete

Either Workspace should not pass this env variable while launching and app - which could break some apps that expect it. 
Or ProjectCenter should not pass it to the build command.

**Comment by trunkmaster** [comment]
Can't reproduce it. My steps are:
- start ProjectCenter from Workspace'
- click menu item "Project->New..."
- select "Application"
- click "Build" button in "Project Builder"
- application builds without any warning

GNUSTEP_USER_ROOT variable was removed from NEXTSPACE on April 9 2019.
What are your setup and steps?

**Comment by onflapp** [comment]
Yes, you are right.

Just tested it and it works.
I must have had old profile somewhere, sorry.
