### ISSUE TITLE
[0.90] TextEdit change save folder when user write document's name

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#296]
Usual steps to save a new document are:

1. open save dialog
1. choose folder
1. write document's name

But writing document's name switch folder to one or two upper folder (tested with several embed folders). Behaviour is not very clear, but folder is allways changed to something upper.

**Comment by trunkmaster** [comment]
@zeroheure can't reproduce this bug now. Do you still have this issue?

**Comment by zeroheure** [comment]
Hi Sergii, I will test in January.

**Comment by trunkmaster** [comment]
@zeroheure any news?

**Comment by zeroheure** [comment]
@trunkmaster  I can't test for now, too busy sorry. But with onflapp's GSDE the issue is gone. Assuming TextEdit is the same, I close this report. I will reopen if it happens on your release.
