### ISSUE TITLE
[0.90] Can't install developer packages because Software Collection is not enabled

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#297]
NextSpace install script doesn't enable Software Collection. Can't install developer packages.

Workaround:

- yum install scl-utils
- yum install centos-release-scl
- yum install llvm-toolset-7.0

Then install NSDeveloper RPMs

**Comment by trunkmaster** [comment]
@zeroheure I guess I fixed it with package dependencies before vacation and re-upload .tgz file to 0.90 release for CentOS 7. Could you please try to reinstall with freshly downloaded release .tgz package?

**Comment by trunkmaster** [comment]
@zeroheure please use latest realease tarball. `nextspace-core-devel` package has dependency on centos-release-scl,
centos-release-scl-rh and llvm-toolset-7.0-clang.

**Comment by trunkmaster** [comment]
Closing as fixed.
