### ISSUE TITLE
[0.90] Workspace crash while opening an empty .app folder

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#298]
Steps on Centos 7.0

1. Create new folder, name it to [something].app
1. Go back to your home dir
1. Double click on folder
1. Workspace crash

**Comment by trunkmaster** [comment]
@zeroheure fixed in master. Check out please.

**Comment by trunkmaster** [comment]
@zeroheure ?

**Comment by trunkmaster** [comment]
Closing as fixed.
