### ISSUE TITLE
Terminal.app + bash is ignoring CTRL+C when launched from Workspace.app

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#300]
Signal handlers seem to be suspended when launching child process directly from Workspace.app. 
For example: Terminal.app -> bash will ignore CTRL+C or windows resize signal.

**Comment by onflapp** [comment]
Is it possible this is related to signals?
Maybe they are blocked.

If I start Terminal.app from the browser view, instead of Dock icon, everything works correctly.
So it must be something wrong with the way WindowMaker is handling the exec.

**Comment by trunkmaster** [comment]
@onflapp I guess it's not signal specific: `zsh` receives CTRL+C whithout problem. Maybe `bash` handles CTRL+C in some specific manner?

**Comment by onflapp** [comment]
Yes, it seems that zsh just unblocks all signals.

I was able to reproduce it with other shells as well.
https://github.com/trunkmaster/nextspace/pull/306 fixes the problem

**Comment by trunkmaster** [comment]
I've merged PR #306, thank you. I guess this issue can be closed.
