### ISSUE TITLE
Workspace Manager quit with error on build from master

### ISSUE THREAD

**Issue by LarBob** [trunkmaster/nextspace#31]
![image](https://user-images.githubusercontent.com/5503528/45720139-18687e80-bb71-11e8-80e0-40d24ed731fc.png)

This is on a fresh CentOS 7 minimal install after following the build and install instructions.

**Comment by trunkmaster** [comment]
OK, I'll check it with fresh install.

**Comment by LarBob** [comment]
Okay, /Users/larbob was empty so I created it and moved the contents of System/etc/skel/Library to it. No dice though.

**Comment by LarBob** [comment]
Still no dice. :(

**Comment by trunkmaster** [comment]
Send me a console.log. It is located in /tmp/GNUstep<uid> directory.

**Comment by LarBob** [comment]
```
/usr/NextSpace/Apps/Workspace.app/Workspace: error while loading shared libraries: libWUtil.so.5: cannot open shared object file: No such file or directory
Stopping GNUstep services: gpbs gdnc.
```

**Comment by LarBob** [comment]
Ah yes, that fixed it. Thank you! (should have realized..)

![image](https://user-images.githubusercontent.com/5503528/45848882-1253d880-bcfe-11e8-835b-39dec776a63b.png)

Now there is this issue with the titlebar fonts, but other than that it seems to be working

**Comment by trunkmaster** [comment]
Great! I hope after I release new RPM packages installation process will run more smoothly. Please close the issue if it's considered resolved.

**Comment by LarBob** [comment]
Thanks!
