### ISSUE TITLE
cannot open console.log

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#312]
I have problem on my Debian
It seems like 
GS_SECURE="/tmp/GNUstepSecure"$UID

doesn't work properly because $UID is going to be empty string
using "id -u" solves the problem
e.g.
GS_SECURE="/tmp/GNUstepSecure"\`id -u\`

**Comment by trunkmaster** [comment]
Fixed in master. Please use latest version of `System/etc/profile.d/nextspace.sh`.

**Comment by trunkmaster** [comment]
@onflapp ?

**Comment by onflapp** [comment]
@trunkmaster the console on Debian works now. Thanks!
