### ISSUE TITLE
TextEdit toggle bold/italic doesn't work

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#313]
Making selection bold works as expected.
However, "Unbold" does not.

NSFontManager should manage items in the Fonts menu by setting appropriate tag and title based on text selection.
This does not seem to happen because NSFontManager does not know about the Fonts menu.

**Comment by onflapp** [comment]
After a lot of testing, I am quite confident the problem is in NSFontManager not managing the Font menu.
If the Font menu is create problematically, there is no problem. 
However, Font menu and NSFontManager are both initiated in the Gorm file.

I would expected that the Gorm file loader would connect the Font menu to the NSFontsManager instance.
Can someone with knowledge of Gorm comment on this?
Would this be Gorm.app problem or GNUStep?

If I connect the Fonts menu to NSFontManager programmatically, everything works as expected.
e.g.

`
NSMenu* f = [[[[[NSApp mainMenu] itemWithTitle:@"Format"] submenu]itemWithTitle:@"Font"] submenu];
[[NSFontManager sharedFontManager] setFontMenu:f];
`

**Comment by trunkmaster** [comment]
Fixed.
