### ISSUE TITLE
Debian: gnustep-services: [ unexpected operator

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#316]
The script /usr/NextSpace/bin/gnustep-services
fails to execute on Debian. 

/usr/NextSpace/bin/gnustep-services: 57: [: /bin/zsh: unexpected operator

I think the problem is that the script itself is using "/bin/sh" and then sourcing /etc/profile.d/nextstep.sh which is using syntax "/bin/sh" doesn't understand (?)

Changing shell to #!/bin/bash fixes the problem.

**Comment by trunkmaster** [comment]
@onflapp hm... strange `gnustep-services` is 50-line long (I suppose `57` is a line number). 
Where have you got this error from, console.log? How do you run `gnustep-services`?
Show me please your `/etc/profile.d/nextspace.sh` and `/usr/NextSpace/bin/gnustep-services`.

**Comment by onflapp** [comment]
Strange indeed. My only explanation is that  line 57 comes from the /etc/profile.d/nextspace.sh script which is sourced by the /usr/NextSpace/bin/gnustep-services

**Comment by onflapp** [comment]
@trunkmaster I don't think /bin/sh in Debian is actually bash, that's why it is failing.
In some other distros (RedHat?) it is just a symlink.

**Comment by onflapp** [comment]
when testing it in terminal:
`
$ /bin/bash /usr/NextSpace/bin/gnustep-services -> works
$ /bin/sh /usr/NextSpace/bin/gnustep-services -> does not
`

**Comment by trunkmaster** [comment]
@onflapp show me `ls -l /bin/sh` output.

**Comment by onflapp** [comment]
it is "dash"

**Comment by zeroheure** [comment]
Yes, Debian default shell is Dash since Debian Jessie (Debian 8).

**Comment by trunkmaster** [comment]
@onflapp I've installed `dash` on CentOS and found that problems is in `/etc/profile.d/nextspace.sh`.

**Comment by trunkmaster** [comment]
@zeroheure thanks. I've made a lot fixes to your issues. Please take a look at them and give me a feedback.

**Comment by zeroheure** [comment]
@trunkmaster just change the shebang to Bash. Bash is allways installed in Centos, Fedora and Debian. Add a package dependency to be sure.

**Comment by trunkmaster** [comment]
@zeroheure I'd better make scripts POSIX-compliant. :)

**Comment by zeroheure** [comment]
@trunkmaster See [this short exlpanation of differences between Dash and Bash](https://lkhill.com/binsh-checking-for-bash-vs-dash-incompatibilities/). Dash is very limnited (but fast). [Checkbashisms script](https://sourceforge.net/projects/checkbaskisms/) will help if you want to clean the startup script.

**Comment by zeroheure** [comment]
@trunkmaster I've seen your fixes. Will test them in a few days, lack of time.

**Comment by trunkmaster** [comment]
@onflapp fixed. Try new nextspace.sh profile.

**Comment by onflapp** [comment]
works properly now
