### ISSUE TITLE
[0.90] CentOS8 Can't install developer packages because couldn't resolve package dependencies

### ISSUE THREAD

**Issue by wynn1212** [trunkmaster/nextspace#320]
When installer prompt to install NEXTSPACE Development package in CentOS8. dnf throw the following error:
```
Error: 
 Problem 1: conflicting requests
  - nothing provides libbytesize(x86-64) = 1.4-1.el8 needed by libbytesize-devel-1.4-1.el8.x86_64
 Problem 2: conflicting requests
  - nothing provides giflib-devel needed by libwraster-devel-5.0.0-0.el8.x86_64
```

The problem 2 can be resolved by enabling power tools repository in CentOS 8.
 
But the problem 1 cannot be resolve due to `libbytesize(x86-64) = 1.4-1.el8` is no longer available in the repository. The latest available in the repository is `libbytesize(x86-64) = 1.4-3.el8`

**Comment by trunkmaster** [comment]
@wynn1212 thanks for the report. I'll remove development packages from CentOS 8 tarball and change `nextspace_install.sh` to skip installation of them.

**Comment by trunkmaster** [comment]
We have 2 options:
1. Disable development packages on CentOS 8.
2. Rebuild -devel packages every time YUM repo update non-devel packages.

I'm for option 1.
If you want to make development, please use CentOS 7 and appropriate NEXTSPACE release file.

**Comment by wynn1212** [comment]
Consider this problem solved.
Should I close this issue?

**Comment by trunkmaster** [comment]
@wynn1212 could you please share your solution?

**Comment by wynn1212** [comment]
This is my temporarily solution. Not guarantee it'll work on next major update.
For some reason `libbytesize-devel` is available on CentOS Stream PowerTools Repository.  But not on CentOS 8.

Temporarily solution is install `libbytesize-devel-1.4-3.el8.x86_64.rpm` from CentOS Stream PowerTools Repository.

**Comment by trunkmaster** [comment]
@wynn1212 I've checked CentOS Stream. Currently it has libudisks2-devel so there's no need to build it thus no need to have libbytesize-devel. I think CentOS Stream should be minimum required version for 8 release branch.

P.S.: Thanks for the hint, I'm seriously thinking about moving my development to CentOS Stream. I see a lot of advantages from developer perspective: Emacs with lsp-mode+clangd+treemacs, clang 11, libdispatch 5.3.

**Comment by trunkmaster** [comment]
CentOS 8 now contains libudisks2-devel (as well as libbytesize-devl) in PowerTools repository. Closing issue.
