### ISSUE TITLE
Distribution/release [for ARM]: Update libobjc2 to version 2.1.1 as soon as published [title updated]

### ISSUE THREAD

**Issue by Letterus** [trunkmaster/nextspace#329]
libobjc2 2.0 will not build for Linux ARM (armhf/arm64) until https://github.com/gnustep/libobjc2/commit/4cf4ad145cfcd8fd08f90157d851c2374ac32151, see https://github.com/gnustep/libobjc2/issues/164.

Please include that version for the next release. This is especially relevant for Debian Packaging when it comes to Raspbian, @pgeorgi.

**Comment by trunkmaster** [comment]
@Letterus thanks for info. I think it should be better to wait for new libobjc2 release.

**Comment by Letterus** [comment]
@trunkmaster There now is a new release of libobjc2, v2.1.

https://github.com/gnustep/libobjc2/releases/tag/v2.1

Would be great if you could update that dependency. Please take into account that libobjc2 now depends on submodules, so you either have to init those via git or load the dependencies as tarballs (see release notes).

**Comment by trunkmaster** [comment]
@Letterus thanks, I'll update dependencies after some testing of new libobjc2 version.

**Comment by trunkmaster** [comment]
@Letterus I've updated SPEC file to a new release. Check it out.

**Comment by Letterus** [comment]
Great, thank you!

@pgeorgi  Would you mind adopting this update for the Debian packaging? That would be nice.

**Comment by pgeorgi** [comment]
@Letterus See #338

**Comment by Letterus** [comment]
> @Letterus See #338

Arr. Great, really happy about that. Trying again to apply that on ARM soon. Thank you!

(Thank you for the documentation as well. I'm going to try to learn how this Debian packaging works. It works great on my system, so it must be great, but I did not really get it yet. ;-))

**Comment by trunkmaster** [comment]
@Letterus has this issue resolved?

**Comment by Letterus** [comment]
To be true: Not completely. It appeared that libobjc 2.1 contains bug https://github.com/gnustep/libobjc2/issues/177 which was only fixed after the release of 2.1. For the Debian build this is currently fixed by a patch, but it might be that for the next release you will need to rely on the release of 2.1.1.

**Comment by trunkmaster** [comment]
@Letterus current libobjc2 2.1 builds successfully on x86_64. Is it true for ARM? If answer is "yes", switch to version 2.1.1 or 2.2 should be a separate issue. If - "no" please reopen the issue and change title and description.

**Comment by Letterus** [comment]
@trunkmaster This applied for a VM on x86_64. So I expect you to run into build issues at some time at the same point as well. I think this should be reopened and release 1.0 should contain libobjc2 2.1.1 or 2.2.

**Comment by Letterus** [comment]
Please note that building libobjc2 (throwing a warning though) worked well, but linking against libobjc2 of subsequent builds failed at the point mentioned.

**Comment by trunkmaster** [comment]
@Letterus to make things clearer to me:
1. Current libobjc2 2.1 has not described issue with (warnings) during compilation niether on x86_64 nor on ARM. Is it a correct?
2. libobjc2 development `master` branch has issue and hopefully will be fixed in upcoming new release. Correct?

If answers to both questions is "yes" - titled problem is potential issue on libobjc2 version upgrade. Am I right?

**Comment by Letterus** [comment]
> @Letterus to make things clearer to me:
@trunkmaster It's even more complicated:

> 
>     1. Current libobjc2 2.1 has not described issue (warnings) during compilation niether on x86_64 nor on ARM. Is it a correct?

The bug existed as part of the 2.1 release *tarball* and was fixed within the 2.1 release *tag*. It should be fixed with a new 2.1.1 release tarball (or just use the git tag). I expect that issue to affect amd64 as well as ARM.

> 
>     2. libobjc2 development `master` branch has issue and hopefully will be fixed in upcoming new release. Correct?

No. It's already fixed in master as of https://github.com/gnustep/libobjc2/commit/365e53632e8be41e49f21ee47a63e41be424a237.

> If answers to both questions is "yes" - titled problem is potential issue on libobjc2 version upgrade. Am I right?

No. ;-) You will need to upgrade or to use the 2.1 git tag to avoid the bug introduced with the 2.1 tarball.

**Comment by trunkmaster** [comment]
@Letterus great. Thank you for explanations. Reopening issue.

**Comment by trunkmaster** [comment]
I assume that issue was fixed. Please reopen if needed.
