### ISSUE TITLE
libdispatch link in the wiki

### ISSUE THREAD

**Issue by alexmyczko** [trunkmaster/nextspace#33]
You probably want to also point to https://github.com/nickhutchinson/libdispatch for people that want to build everything from source.

**Comment by trunkmaster** [comment]
Why? That people can use a .tgz with cloned sources from Apple repo and couple of patches in Libraries/dispatch. Build instructions are in libdispatch.spec. Isn't it enough?

**Comment by alexmyczko** [comment]
I wasn't aware the Apple version works out of the box for Linux...

**Comment by trunkmaster** [comment]
If you'll look into `Libraries/dispatch` directory you find 2 quite trivial CentOS/RHEL-specific patches to original Apple's libdipatch. Everything else is working out of the box.
