### ISSUE TITLE
Timezone is hardcoded

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#334]
@trunkmaster The initial value of timezone is hardcoded to Europe/Kiev

Library/Preferences/GlobalDefaults.plist
    <key>Local Time Zone</key>
    <string>Europe/Kiev</string>

Can this setting be removed to take default value from the system?

**Comment by trunkmaster** [comment]
@onflapp fixed. Check it out,

**Comment by trunkmaster** [comment]
@onflapp ?

**Comment by onflapp** [comment]
Fixed, thanks!
