### ISSUE TITLE
Useful apps completing the Nextspace experience

### ISSUE THREAD

**Issue by Letterus** [trunkmaster/nextspace#340]
Starting this issue to collect which apps would be useful to complete the Nextspace experience.

I'd suggest to concentrate on those apps

- which either already exist or seem to have a chance to be somewhat easily realized or ported
- which are known to provide APIs or integrate very well into existing frameworks and the overall UX (from NextStep or Mac OS X) and thus provide additional benefit over existing apps from other desktop projects
- one would expect as really necessary to provide a useful UX

Apps that I suggest and (existing) implementations:

- Image and PDF preview:
   - Review: https://github.com/trunkmaster/nextspace/tree/master/Applications/Review ?
   - LaternaMagica: http://www.nongnu.org/gap/laternamagica/index.html
   - GSPdf: http://www.nongnu.org/gap/gspdf/index.html
- Setup printing (CUPS frontend): ??
- Terminal: https://github.com/trunkmaster/nextspace/tree/master/Applications/Terminal
- Mail (IMAP): GNUMail - http://www.nongnu.org/gnustep-nonfsf/gnumail/index.html
- Addressbook (CardDAV): AdressManager - http://www.nongnu.org/gap/addresses/index.html
- Calendar (CalDAV): SimpleAgenda - http://wiki.gnustep.org/index.php/SimpleAgenda.app (having Tasks integrated)
- Tasks (CalDAV): ?? - see above
- Text Editor: TextEdit(Plus) - https://github.com/jjgod/TextEditPlus or https://github.com/ericwa/TextEdit
- Compress and expand files: Zipper - http://gap.nongnu.org/zipper/index.html

Some are already part of this project. I don't know if further apps should become part of this project. But maybe somebody wants to start working on one of these and inspect it for its usefulness and ways to develop it and to integrate it into Nextspace. This might be part of a separate project.

**Comment by stepcity** [comment]
Many of these are already implemented in Nextspace, although you clearly knew that. I think this as a separate project is a good idea, a set of forks of these applications that are modified to be well integrated with Nextspace would be very nice.

**Comment by jasaldivara** [comment]
Some nice Gnustep Apps that I think could complement the Nextspace Desktop:

- Code Editor: Gemas -> https://www.nongnu.org/gnustep-nonfsf/gemas/index.html
- Music Player: Cynthiune -> https://www.nongnu.org/gap/cynthiune/index.html
- Vector-based drawing: Graphos -> http://gap.nongnu.org/graphos/
- PDF Viewer: Vindaloo (A.K.A. ViewPDF) -> https://packages.debian.org/unstable/gnustep/viewpdf.app IMHO It's user interface looks cleaner and more polished than GSPdf
- Icon and pixel art editor: PikoPixel -> http://twilightedge.com/mac/pikopixel/index.html

**Comment by Letterus** [comment]
Closing this issue for now.
