### ISSUE TITLE
2.build_applications.sh script build fails.

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#356]
#### Reproduced in: Centos 7, 8 and 8 Stream

>  Compiling file Processes/Processes.m ...
>  Compiling file Processes/FileMoverUI.m ...
>  Compiling file Processes/BGProcess.m ...
>  Linking app Workspace ...
> /usr/NextSpace/lib/libwraster.so: undefined reference to 'RLoadWEBP'
> /usr/NextSpace/lib/libwraster.so: undefined reference to 'RReleaseMagick'
> /usr/NextSpace/lib/libwraster.so: undefined reference to 'RLoadMagick'
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[4]: *** [/Developer/Makefiles/Instance/application.make:133: Workspace.app/./Workspace] Error 1
> gmake[3]: *** [/Developer/Makefiles/Instance/application.make:147: internal-app-run-compile-submake] Error 2
> gmake[2]: *** [/Developer/Makefiles/Master/rules.make:297: Workspace.all.app.variables] Error 2
> gmake[1]: *** [/Developer/Makefiles/Master/application.make:38: internal-all] Error 2
> make: *** [/Developer/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.JfvHls (%build)

**Comment by trunkmaster** [comment]
@armm77 Thanks, fixed by latest commit. Check it.

**Comment by armm77** [comment]
@trunkmaster , only 1 left.
>  Compiling file Processes/BGProcess.m ...
>  Linking app Workspace ...
> /usr/NextSpace/lib/libwraster.so: undefined reference to 'RLoadWEBP'
> clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[4]: *** [/Developer/Makefiles/Instance/application.make:133: Workspace.app/./Workspace] Error 1
> gmake[3]: *** [/Developer/Makefiles/Instance/application.make:147: internal-app-run-compile-submake] Error 2
> gmake[2]: *** [/Developer/Makefiles/Master/rules.make:297: Workspace.all.app.variables] Error 2
> gmake[1]: *** [/Developer/Makefiles/Master/application.make:38: internal-all] Error 2
> make: *** [/Developer/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.LSFJIr (%build)

**Comment by trunkmaster** [comment]
@armm77 I can't reproduce it, sorry. Could you please try clean build? Please show your libwraster/config.h contents after build.

**Comment by armm77** [comment]
@trunkmaster, you are correct, I made a new virtual machine and it was built correctly. 

Although I could not log in.
