### ISSUE TITLE
Updates on Debian/Ubuntu?

### ISSUE THREAD

**Issue by felixding** [trunkmaster/nextspace#359]
I've been following the project for quite a while. There were many PRs and discussions about Debian packaging a few months ago but it seems that progress on Debian has stalled recently. Can't help wondering what's the status on this subject?

Just switched to a ThinkPad from a Mac. The first thing I want to do is install Nextspace. 😃

**Comment by alexmyczko** [comment]
There's this one https://github.com/trunkmaster/nextspace/issues/242 but no idea, I'm not a big fan of "rpm" packaging. And looking forward to something .deb based as well...

**Comment by felixding** [comment]
I just found out that there IS a script that builds everything on Debian/Ubuntu! It's just not in the README.me file.

Anyway, I managed to compile and install `nextspace-desktop`, and was able to start it with `sudo systemctl start loginwindow`. But as soon as I logged in, it threw an error "Session failed with error" and gave me two options: `Cleanup` and `Restart`.

I'm stuck here. Any hints? It asked me to check `console.log` which I couldn't find anywhere.

**Comment by armm77** [comment]
@felixding, I don't use NEXTSPACE on ubuntu/debian and I'm not sure if it will work for you, but you could verify that all the initial files of the profile configuration are copied to the user.

**Comment by felixding** [comment]
@armm77 Thanks for the quick reply!

How can I verify that? I guess I don't have the files copied, because I didn't create any user in Nextspace. Instead, I installed it with my existing user.

**Comment by armm77** [comment]
you can create a new user by following the steps of the script. 

https://github.com/trunkmaster/nextspace/blob/fec88a7f0f69f51410651d01e6de79f633d233c1/Packaging/RedHat/nextspace_install.sh#L146

**Comment by felixding** [comment]
Okay. I created a new user following the steps in `nextspace_install.sh`. But after I logged in and run `sudo systemctl start loginwindow`, I got a dark screen with a blinking cursor.

**Comment by armm77** [comment]
@felixding, You could indicate the specifications of your system to be able to replicate the incident.

**Comment by felixding** [comment]
Sure.

I'm using Linux Mint 20.10 Xfce Edition.

Another update: I successfully logged in to Nextspace desktop with the new
user. There was an Ubuntu icon in the upper right corner, like a dock app.
But I could do nothing with this icon or anywhere else on the screen - I
tried single/double/right click but nothing happened. Eventually I had to
kill X with shortcuts and went back to Xfce from command line.

Currently I'm fiddling with Window Maker and imagining  what a complete UX
Nextspace would be. Maybe I should try it in a VM (I did but that was like
two years ago).

**Comment by armm77** [comment]
Hi @felixding, I tell you that I work with ubuntu focal, and I got some points, I have to correct, the deb packages are generated correctly, but in the installation the libraries and programs are not installed where they should go, I had to make several manual changes to get a half performance.

If you want to continue you must extract this package in the root of the user me (/Users/me). Although I suggest you try the packages or the installer for centos.
[Library.tar.gz](https://github.com/trunkmaster/nextspace/files/6017866/Library.tar.gz)

You must install the zsh shell and make the links that I show you in the txt. 
[fix.txt](https://github.com/trunkmaster/nextspace/files/6017888/fix.txt)
![Captura de Pantalla 2021-02-21 a la(s) 08 47 28](https://user-images.githubusercontent.com/3104815/108628468-264d1880-7429-11eb-986a-fe85ffb3d540.png)

**Comment by felixding** [comment]
Thanks!

I managed to install Nextspace on Fedora 31 (Cent OS didn't work for me).

Finally a desktop environment that uses Command as the modifier key! I wish there's a way to make a default for other apps on Nextspace as well (for example Firefox). I know we can remap key bindings using Kinto/xkeysnail, but having a consistent key binding as a default on Nextspace would the best!

**Comment by armm77** [comment]
I am sure that in the future there will be many more applications and many improvements. 👍🏼
