### ISSUE TITLE
Futura Narrow font in Login.app

### ISSUE THREAD

**Issue by alexmyczko** [trunkmaster/nextspace#36]
For the boot up plymouth theme or login.app in nextspace generally do you plan to add futura (like fonts), and use it in login.app? Or just a graphic of it?

I have a suggestion of the font League Spartan (however there's no italic, nor narrow version as of now):
https://github.com/sursly/league-spartan

I had packaged it for debian, but centos/fedora still doesn't have it:
https://repology.org/metapackage/fonts:league-spartan/versions

Helvetica also has a great clone, called Nimbus Sans L, albeit also not very complete like the original...

For reference: https://www.youtube.com/watch?v=2BsqgXsO9EE

**Comment by armm77** [comment]
It is interesting proposal, I had made a theme for plymouth with the same opening sequence of openstep, but I did not dare to upload it.

**Comment by alexmyczko** [comment]
If you still have it, could I have a copy to test it? Maybe you dare to upload it now?

**Comment by trunkmaster** [comment]
@alexmyczko,
1. I don't plan to add Futura fonts into repo tree but I plan to recreate Login and Plymouth panel with "NEXTSPACE" text as image. I have some Futura fonts, but thank you for the hint about "League Spartan".
2. "Nimbus Sans L" lacks bitmap fonts for using without antialiasing (which I prefer for now).

**Comment by armm77** [comment]
Yes, of course, I'm going to make some changes and upload it to see your opinions.

**Comment by armm77** [comment]
the images are 16x16, could reduce the size if it seems more appropriate. What would be the right size? 5x5? 8x8?

**Comment by trunkmaster** [comment]
I suggest to use 'Frameworks/NXAppKit/Resources/Cursors/images/watch.png' as a starting image. I suppose you could you affine transformations to create 4 sharp images of spinning disk. The size of png is 24x24 pixels but actual image is a 16x16.

**Comment by armm77** [comment]
hello @trunkmaster  change the image you suggested review it when you can and tell me.
[nextspace.zip](https://github.com/trunkmaster/nextspace/files/2490164/nextspace.zip)

**Comment by trunkmaster** [comment]
@alexmyczko, are you happy with current plymouth configuration?

**Comment by alexmyczko** [comment]
@trunkmaster got a gif showing it? or a screenshot?

**Comment by trunkmaster** [comment]
@alexmyczko, hmm... I expect you try it yourself. Anyway, here is a rough visualization:
![NEXTSPACE](https://user-images.githubusercontent.com/23114975/70322878-fcafcd80-1833-11ea-8001-828b57e54a97.gif)
.

**Comment by trunkmaster** [comment]
@alexmyczko, may I close this issue?
