### ISSUE TITLE
Documentation for installing compilers/libraries needed to compile Gnustep apps

### ISSUE THREAD

**Issue by packetrhino** [trunkmaster/nextspace#360]
First, the NEXTSPACE install looks really nice!  The feel is very much like the original , more integrated than regular WMaker etc.

I tried to download and install the compilers and libraries so that I could compile and install TalkSoup (IRC client) but ran into issues.

Please document the steps needed under CentOS7 to install what is needed, without accidentally interfering with the NEXTSPACE libraries and runtime.

**Comment by trunkmaster** [comment]
@packetrhino you don't need any special steps except installed development packages (-dev). I've compiled and installed netclasses and TalkSoup without any problems. What error have you got?

**Comment by packetrhino** [comment]
I have the following installed:

nextspace-applications.x86_64 : NextSpace desktop core applications.
nextspace-core.x86_64 : NextSpace filesystem hierarchy and system files.
nextspace-frameworks.x86_64 : NextSpace core libraries.
nextspace-gnustep.x86_64 : GNUstep libraries.

When I search for gnustep, I see:

============================= N/S matched: gnustep =============================
gnustep-base.x86_64 : GNUstep Base library package
gnustep-base-devel.x86_64 : Header of the GNUstep Base library packes
gnustep-base-doc.noarch : Documentation for gnustep-base
gnustep-base-libs.x86_64 : GNUStep Base Libraries
gnustep-filesystem.x86_64 : The basic directory layout for GNUstep packages
gnustep-make.x86_64 : GNUstep makefile package
gnustep-make-doc.noarch : Documentation for gnustep-make
nextspace-gnustep.x86_64 : GNUstep libraries.
libobjc2.x86_64 : GNUstep Objecttive-C runtime library.

Which of these packages, should be added?  I just want to be sure I don't end up with conflicting versions.

rpm -qa is attached.
[rpmqa.txt](https://github.com/trunkmaster/nextspace/files/5997777/rpmqa.txt)

**Comment by armm77** [comment]
Hello @packetrhino in your rpmqa.txt I did not see any dev package, it is necessary that you install it to build other projects that depend on the gnustep library.

**Comment by armm77** [comment]
@packetrhino from the NSDeveloper folder install the * -devel- * and try to build again. 
https://github.com/trunkmaster/nextspace/releases/download/0.90/NextSpace-0.90-CentOS_7.tgz

**Comment by packetrhino** [comment]
Hi,  thank you, that was the information I needed!  I did find that I needed to add in by hand, the repository centos-release-sc1 so that the llvm-toolset-* could be found.

**Comment by trunkmaster** [comment]
@armm77 thank you.
@packetrhino is this issue should be considered as resolved?

**Comment by packetrhino** [comment]
Yes, I have successfully compiled TalkSoup using the above.
