### ISSUE TITLE
Workspace Crashes

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#365]
Adding a new application to the dock crashes the workspace. 

This happens when a new application is being added and the icon does not exist previously in the path ~/Library/Workspace/CachedPixmaps/ (it is a new application, it is normal that the icon does not exist).

**Step to reproduce the behavior**

1. Compile or install a new application.
2. Drag the application to the dock.

**Steps to not reproduce the behavior**

1. Compile or install a new application.
2. Run the application, this will create the application icon in the established path.
3. Drag the application to the dock and it works as expected.

**Comment by trunkmaster** [comment]
@armm77 confirmed. I'll look into this.

**Comment by armm77** [comment]
Solved. Brilliant @trunkmaster 👍🏼
