### ISSUE TITLE
i got the Nextspace "system coming up " screeen but not the workspace

### ISSUE THREAD

**Issue by hubertz** [trunkmaster/nextspace#366]

**Comment by trunkmaster** [comment]
@hubertz `loginwindow` service won't start for some reason. More info needed.

**Comment by trunkmaster** [comment]
@hubertz ?

**Comment by hubertz** [comment]
sorry! i made a clean install and everything worked fine

**Comment by trunkmaster** [comment]
clould you please close the issue?
