### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by Ballagyr** [trunkmaster/nextspace#367]
How do you remove this? This thing has changed my entire system. I want my system the way it was before!

**Comment by armm77** [comment]
As root run the following command: 

**rpm -qa | grep nextspace**

Remove the packages with the following sequence:

nextspace-applications-devel-0.91-0.el8.x86_64
nextspace-applications-0.91-0.el8.x86_64
nextspace-frameworks-devel-0.90-2.el8.x86_64
nextspace-frameworks-0.90-2.el8.x86_64
nextspace-gnustep-devel-1_27_0_nextspace-1.el8.x86_64
nextspace-gnustep-1_27_0_nextspace-1.el8.x86_64
nextspace-core-devel-0.95-11.el8.x86_64
nextspace-core-0.95-11.el8.x86_64

**Comment by Ballagyr** [comment]
After removal, xorg stopped starting. As shown in the first image.
https://imgur.com/joXLZyT

However, after I type "startx", in hopes of getting Mate is back, the xorg's crashed.
https://imgur.com/8Pbplvy

The problem has already been solved, but this is a bomb.

The project itself is interesting and I liked the project, but I don't want to make Linux stop being Linux, I just wanted to use an alternative to WindowMaker. The script changes the system so much for nothing, because the main thing, which would be to see the desktop environtment start, did not happen.

I hope the project will focus on being a complete and stable desktop environment and forget about this desire to transform Linux on a NEXTStep.

**Comment by trunkmaster** [comment]
@Ballagyr if you install some project while it's in active development be prepared to some weird things. Could you please tell us about your solution?
