### ISSUE TITLE
Package conflict while installing

### ISSUE THREAD

**Issue by redroote** [trunkmaster/nextspace#37]
I was trying to install nextspace following "Build and install guide"

I encountered following error :
	
	--> Processing Conflict: nextspace-gnustep-1.24.8_0.24.1-10.el7.centos.x68_64 conflicts gnustep-filesystem
	--> Finished Dependency Resolution
	Error: nextspace-gnustep conflicts with gnustep-filesystem-2.7.0-1.el7.x86_64

It was at the end of :
	# yum install `grep "BuildRequires" nextspace-gnustep.spec | awk -c '{print $2}'`

Any suggestion how to resolve this ?

**Comment by trunkmaster** [comment]
Just remove `gnustep-filesystem` package: `yum erase gnustep-filesystem` and any original gnustep packages. 

Did you install this package manually? If not, at what step in "Build and install guide" this happened?
Note: it's not a dependency of any nextspace packages.

**Comment by redroote** [comment]
Thank you for the reply.

>  Did you install this package manually?
No.  I didn't 

>  at what step in "Build and install guide" this happened?
It was..
**3. Build NEXTSPACE**
5.  Install required development packages as `root`:
# yum install `grep "BuildRequires" nextspace-gnustep.spec | awk -c '{print $2}'`

And here is the output.  I hope this helps.

> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: centos.mirror.cdnetworks.com
>  * epel: mirror.premi.st
>  * extras: centos.mirror.cdnetworks.com
>  * updates: centos.mirror.cdnetworks.com
> Package matching clang-3.4.2-8.el7.x86_64 already installed. Checking for update.
> Resolving Dependencies
> --> Running transaction check
> ---> Package cups-devel.x86_64 1:1.6.3-35.el7 will be installed
> --> Processing Dependency: zlib-devel for package: 1:cups-devel-1.6.3-35.el7.x86_64
> --> Processing Dependency: krb5-devel for package: 1:cups-devel-1.6.3-35.el7.x86_64
> ---> Package freetype-devel.x86_64 0:2.4.11-15.el7 will be installed
> ---> Package giflib-devel.x86_64 0:4.1.6-9.el7 will be installed
> ---> Package gnustep-make.x86_64 0:2.7.0-1.el7 will be installed
> --> Processing Dependency: gnustep-filesystem(x86-64) = 2.7.0-1.el7 for package: gnustep-make-2.7.0-1.el7.x86_64
> ---> Package gnutls-devel.x86_64 0:3.3.26-9.el7 will be installed
> --> Processing Dependency: gnutls-dane(x86-64) = 3.3.26-9.el7 for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: gnutls-c++(x86-64) = 3.3.26-9.el7 for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: pkgconfig(p11-kit-1) for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: pkgconfig(nettle) for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: pkgconfig(libtasn1) for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: pkgconfig(hogweed) for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: libgnutlsxx.so.28()(64bit) for package: gnutls-devel-3.3.26-9.el7.x86_64
> --> Processing Dependency: libgnutls-dane.so.0()(64bit) for package: gnutls-devel-3.3.26-9.el7.x86_64
> ---> Package libX11-devel.x86_64 0:1.6.5-1.el7 will be installed
> --> Processing Dependency: pkgconfig(xcb) >= 1.11.1 for package: libX11-devel-1.6.5-1.el7.x86_64
> --> Processing Dependency: pkgconfig(xproto) for package: libX11-devel-1.6.5-1.el7.x86_64
> --> Processing Dependency: pkgconfig(xcb) for package: libX11-devel-1.6.5-1.el7.x86_64
> --> Processing Dependency: pkgconfig(kbproto) for package: libX11-devel-1.6.5-1.el7.x86_64
> ---> Package libXcursor-devel.x86_64 0:1.1.14-8.el7 will be installed
> --> Processing Dependency: pkgconfig(xrender) for package: libXcursor-devel-1.1.14-8.el7.x86_64
> ---> Package libXext-devel.x86_64 0:1.3.3-3.el7 will be installed
> ---> Package libXfixes-devel.x86_64 0:5.0.3-1.el7 will be installed
> ---> Package libXmu-devel.x86_64 0:1.1.2-2.el7 will be installed
> ---> Package libXt-devel.x86_64 0:1.1.5-3.el7 will be installed
> --> Processing Dependency: pkgconfig(sm) for package: libXt-devel-1.1.5-3.el7.x86_64
> --> Processing Dependency: pkgconfig(ice) for package: libXt-devel-1.1.5-3.el7.x86_64
> ---> Package libao-devel.x86_64 0:1.1.0-8.el7 will be installed
> ---> Package libart_lgpl-devel.x86_64 0:2.3.21-10.el7 will be installed
> ---> Package libffi-devel.x86_64 0:3.0.13-18.el7 will be installed
> ---> Package libicu-devel.x86_64 0:50.1.2-15.el7 will be installed
> ---> Package libjpeg-turbo-devel.x86_64 0:1.2.90-5.el7 will be installed
> ---> Package libpng-devel.x86_64 2:1.5.13-7.el7_2 will be installed
> ---> Package libsndfile-devel.x86_64 0:1.0.25-10.el7 will be installed
> ---> Package libtiff-devel.x86_64 0:4.0.3-27.el7_3 will be installed
> ---> Package libxml2-devel.x86_64 0:2.9.1-6.el7_2.3 will be installed
> ---> Package libxslt-devel.x86_64 0:1.1.28-5.el7 will be installed
> --> Processing Dependency: libgcrypt-devel for package: libxslt-devel-1.1.28-5.el7.x86_64
> ---> Package mesa-libGL-devel.x86_64 0:17.2.3-8.20171019.el7 will be installed
> --> Processing Dependency: pkgconfig(xdamage) >= 1.1 for package: mesa-libGL-devel-17.2.3-8.20171019.el7.x86_64
> --> Processing Dependency: pkgconfig(libdrm) >= 2.4.75 for package: mesa-libGL-devel-17.2.3-8.20171019.el7.x86_64
> --> Processing Dependency: pkgconfig(xxf86vm) for package: mesa-libGL-devel-17.2.3-8.20171019.el7.x86_64
> --> Processing Dependency: gl-manpages for package: mesa-libGL-devel-17.2.3-8.20171019.el7.x86_64
> ---> Package nss-softokn-freebl-devel.x86_64 0:3.36.0-5.el7_5 will be installed
> ---> Package openssl-devel.x86_64 1:1.0.2k-12.el7 will be installed
> ---> Package xz-devel.x86_64 0:5.2.2-1.el7 will be installed
> --> Running transaction check
> ---> Package gl-manpages.noarch 0:1.1-7.20130122.el7 will be installed
> ---> Package gnustep-filesystem.x86_64 0:2.7.0-1.el7 will be installed
> ---> Package gnutls-c++.x86_64 0:3.3.26-9.el7 will be installed
> ---> Package gnutls-dane.x86_64 0:3.3.26-9.el7 will be installed
> --> Processing Dependency: libunbound.so.2()(64bit) for package: gnutls-dane-3.3.26-9.el7.x86_64
> ---> Package krb5-devel.x86_64 0:1.15.1-19.el7 will be installed
> --> Processing Dependency: libkadm5(x86-64) = 1.15.1-19.el7 for package: krb5-devel-1.15.1-19.el7.x86_64
> --> Processing Dependency: libverto-devel for package: krb5-devel-1.15.1-19.el7.x86_64
> --> Processing Dependency: libselinux-devel for package: krb5-devel-1.15.1-19.el7.x86_64
> --> Processing Dependency: libcom_err-devel for package: krb5-devel-1.15.1-19.el7.x86_64
> --> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.15.1-19.el7.x86_64
> ---> Package libICE-devel.x86_64 0:1.0.9-9.el7 will be installed
> ---> Package libSM-devel.x86_64 0:1.2.2-2.el7 will be installed
> ---> Package libXdamage-devel.x86_64 0:1.1.4-4.1.el7 will be installed
> ---> Package libXrender-devel.x86_64 0:0.9.10-1.el7 will be installed
> ---> Package libXxf86vm-devel.x86_64 0:1.1.4-1.el7 will be installed
> ---> Package libdrm-devel.x86_64 0:2.4.83-2.el7 will be installed
> ---> Package libgcrypt-devel.x86_64 0:1.5.3-14.el7 will be installed
> --> Processing Dependency: libgpg-error-devel for package: libgcrypt-devel-1.5.3-14.el7.x86_64
> ---> Package libtasn1-devel.x86_64 0:4.10-1.el7 will be installed
> ---> Package libxcb-devel.x86_64 0:1.12-1.el7 will be installed
> --> Processing Dependency: pkgconfig(xau) >= 0.99.2 for package: libxcb-devel-1.12-1.el7.x86_64
> ---> Package nettle-devel.x86_64 0:2.7.1-8.el7 will be installed
> --> Processing Dependency: gmp-devel(x86-64) for package: nettle-devel-2.7.1-8.el7.x86_64
> ---> Package p11-kit-devel.x86_64 0:0.23.5-3.el7 will be installed
> ---> Package xorg-x11-proto-devel.noarch 0:7.7-20.el7 will be installed
> ---> Package zlib-devel.x86_64 0:1.2.7-17.el7 will be installed
> --> Running transaction check
> ---> Package gmp-devel.x86_64 1:6.0.0-15.el7 will be installed
> ---> Package keyutils-libs-devel.x86_64 0:1.5.8-3.el7 will be installed
> ---> Package libXau-devel.x86_64 0:1.0.8-2.1.el7 will be installed
> ---> Package libcom_err-devel.x86_64 0:1.42.9-12.el7_5 will be installed
> ---> Package libgpg-error-devel.x86_64 0:1.12-3.el7 will be installed
> ---> Package libkadm5.x86_64 0:1.15.1-19.el7 will be installed
> ---> Package libselinux-devel.x86_64 0:2.5-12.el7 will be installed
> --> Processing Dependency: libsepol-devel(x86-64) >= 2.5-6 for package: libselinux-devel-2.5-12.el7.x86_64
> --> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.5-12.el7.x86_64
> --> Processing Dependency: pkgconfig(libpcre) for package: libselinux-devel-2.5-12.el7.x86_64
> ---> Package libverto-devel.x86_64 0:0.2.5-4.el7 will be installed
> ---> Package unbound-libs.x86_64 0:1.6.6-1.el7 will be installed
> --> Processing Dependency: libevent-2.0.so.5()(64bit) for package: unbound-libs-1.6.6-1.el7.x86_64
> --> Running transaction check
> ---> Package libevent.x86_64 0:2.0.21-4.el7 will be installed
> ---> Package libsepol-devel.x86_64 0:2.5-8.1.el7 will be installed
> ---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed
> --> Processing Conflict: nextspace-gnustep-1.24.8_0.24.1-10.el7.centos.x86_64 conflicts gnustep-filesystem
> --> Finished Dependency Resolution
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
>

**Comment by trunkmaster** [comment]
OK, I've found the cause of the problem: current build of nextspace-gnustep-devel package miss "Provides: gnustep-make" in package info. I'll fix this in next release. As temporary solution I removed BuildRequires dependency to gnustep-make.

**Comment by redroote** [comment]
Thank you trunkmaster.
Your move solved it.  Now I can go on to next step.
Cheers !
