### ISSUE TITLE
Typos on the build guide

### ISSUE THREAD

**Issue by felixding** [trunkmaster/nextspace#395]
`~/nextspace/Packaging/RedHat/0.build_frameworks.sh ~/nextspace` should be `~/nextspace/Packaging/RedHat/1.build_frameworks.sh ~/nextspace`

` ~/nextspace/Packaging/RedHat/0.build_applications.sh ~/nextspace` should be ` ~/nextspace/Packaging/RedHat/2.build_applications.sh ~/nextspace`

**Comment by trunkmaster** [comment]
Fixed, thanks.
