### ISSUE TITLE
Terminal Crashes.

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#399]
When you select the unlimited number of lines and set it to the current window, the whole system crashes.

https://user-images.githubusercontent.com/3104815/138931417-82a132dc-706c-47e0-bfc7-08e583f43b2c.mov

**Comment by trunkmaster** [comment]
Confirmed. Actually this part of Terminal has not been correctly implemented.

**Comment by armm77** [comment]
I can confirm that the VM or my physical equipment no longer shuts down when the event occurs. only a restart of the workspace is presented.

And as an image explains more than 1000 words, I leave a video of the behavior. 

https://user-images.githubusercontent.com/3104815/140520102-d89acfba-9898-487f-960e-a2f89dff9865.mov

**Comment by trunkmaster** [comment]
@armm77 check out new Terminal dynamic scrollback buffer size management. 

Selecting "Unlimited" or number of lines preference doesn't mean that Terminal allocates maximum amount of memory for scrollback buffer to hold specified number of lines. Now it allocates screen by screen until maximum allowed number of lines will be reached while incoming data flows (commands in terminal produce output to Terminal).

**Comment by armm77** [comment]
I checked it and the terminal no longer crashes when selecting the option but I see that it has a limit of 256 lines even if you select unlimited.

![Screen Shot 2024-02-28 at 5 47 54 PM](https://github.com/trunkmaster/nextspace/assets/3104815/b9d34b58-0a7f-4db8-a30d-303216b4883b)

**Comment by trunkmaster** [comment]
Confirmed. In my case it's a 3 times. Also I see some buffer garbage at some point. Will try to find out reason for that behavior...

**Comment by trunkmaster** [comment]
@armm77 now it should work without crash. Check it please.

**Comment by armm77** [comment]
Hi @trunkmaster, I see that it already works as it should, but I see that the configuration is not saved, so it shows in the preference panel that it is selected as unlimited, I close and open it again and it remains set in the preference but it only marks 256 until it is pressed and set again .

https://github.com/trunkmaster/nextspace/assets/3104815/d8444f17-f606-4ca8-ae2d-b2b14e5d83df

**Comment by trunkmaster** [comment]
@armm77 fixed, thanks.

**Comment by armm77** [comment]
@trunkmaster, thanks for correcting it. I close the incident
