### ISSUE TITLE
Hardcoded path in GNUMake.postamble

### ISSUE THREAD

**Issue by BertrandDekoninck** [trunkmaster/nextspace#4]
I've tried to build your NX frameworks on a vanilla GNUstep system to test the apps without scrumbling my installation. NXFoundation and NXSystem build and install fine but there is an issue with NXAppkit on installation. The compiler says : 
`ln -s /usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Images /usr/NextSpace/Images
ln: impossible de créer le lien symbolique « /usr/NextSpace/Images »: Aucun fichier ou dossier de ce type`

which means "impossible to create symbolic link...... No exiting file or folder"

In fact :NXAppkit is installed in my System domain which is : /usr/GNUstep/System and not /usr/NextSpace.

This is hardcoded in your  NXAppkit GNUMakeFile.postamble. 
`after-install::
	ln -s $(DESTDIR)/usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Images /usr/NextSpace/Images
	ln -s $(DESTDIR)/usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Fonts /Library/Fonts

I know your first goal is not compatibility with a vanilla GNUstep installation, but could you find a way to correct this issue ? 
Providing your enhanced Preferences; Terminal and other applications to vanilla GNUstep would be nice.

**Comment by trunkmaster** [comment]
Got it. I'll think about ASAP.

**Comment by trunkmaster** [comment]
Fixed in master branch. Try it and give me a feedback on results.

**Comment by trunkmaster** [comment]
@BertrandDekoninck finally build and install NX framewroks.
