### ISSUE TITLE
Workspace Crashes

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#400]
Creating a folder and renaming it, and selecting the top folder crashes the workspace.  This behavior seems to me to be random, it does not always happen or it does not reproduce in the way it is proposed. 

https://user-images.githubusercontent.com/3104815/140235403-3ea72968-8b4b-4963-9eeb-e534c2cbb4d7.mov

https://user-images.githubusercontent.com/3104815/140235436-b5b85870-9290-4ea9-a6cc-b945af08e1e3.mov

**Comment by trunkmaster** [comment]
I think you've faced several distinct problems here and in issue #399. Several events happend at once:
- application crashes (Terminal) and lead to Workspace's crash (I can't reproduce this - I got only Terminal crash but appicon in Dock became weird);
- Workspace crashes
- Login panel interprets Workspace's crash as "Power Off" request and proceeds to OS shutdown;

So, I plan to stick to following plan:
1. Fix Login problem with Workspace exit status handling.
2. Fix problem in Terminal (I understand what the cause of a problem)
3. Fix problem in Workspace

Well done, thank you!

**Comment by armm77** [comment]
I can confirm that the VM or my physical equipment no longer shuts down when the event occurs. only a restart of the Workspace is presented.

And as an image explains more than 1000 words, I leave a video of the behavior. 

https://user-images.githubusercontent.com/3104815/140519179-355581ac-691f-4cd2-91d8-e252e3f0ff75.mov

**Comment by rmottola** [comment]
I cannot reproduce the crash issue in GWorkspace. I don't know if it depends on specific changes of Workspace or not.

**Comment by armm77** [comment]
hi @rmottola, these are tests on Workspace, i have not done GWorkspace tests.

**Comment by trunkmaster** [comment]
@rmottola, I'ts definitely Workspace-specific issue. I suppose it's somehow connected to using KVO in Image View. It's hard to reproduce this bug for me - I'll investigate it later.

**Comment by trunkmaster** [comment]
@armm77 I guess I've fixed this bug. I can reproduce it no more. Check it out, please.

**Comment by armm77** [comment]
Hi @trunkmaster, I perceive the file manager to be more solid, but I was able to reproduce the event.
I tried on Fedora 35 and CentOS Stream 8, with the latest commits https://github.com/trunkmaster/nextspace/commit/2545727f52228ba7e02a16f0a51cfecffcaf054d.
 
https://user-images.githubusercontent.com/3104815/150061791-3c061c35-e0d3-4168-8494-ef9ffe54fab3.mov

**Comment by trunkmaster** [comment]
hi @armm77 could you please run Workspace under debugger and send be backtrace?
I've put script for that in Applications/Workspace/gdb_Workspace.sh. Here is the short instruction:
1. Login into user session as `armm`
2. Login via SSH as `armm` and `cd` into NEXTSPACE sources Applications/Workspace.
3. Run script `./gdb_Workspace.sh` - this attaches GDB debugger into running Workspace. Wait for GDB to complete its loading.
4. Type `c` and Return to continue running Workspace.
5. Proceed with actions you did in the video. Upon crash Workspace stops responding.
6. Switch to GDB session and type `bt` - it show code calling backtrace.
7. Send me all text you'll see after you've entered `bt`.

**Comment by armm77** [comment]
hi @trunkmaster, with the last commit https://github.com/trunkmaster/nextspace/commit/bfb80b702dae3860795f285234c2045a8ef65c57 I couldn't get it to fail, but the following video support was presented.


https://user-images.githubusercontent.com/3104815/150233160-4827d79b-9688-41c7-b550-675211494682.mov

[test2.txt](https://github.com/trunkmaster/nextspace/files/7901097/test2.txt)

**Comment by trunkmaster** [comment]
Confirmed, thanks.

**Comment by trunkmaster** [comment]
@armm77 the problem should be fixed with latest commit. Please check.

**Comment by armm77** [comment]
Hi @trunkmaster, the initial error is no longer replicated, but I have a problem when renaming the folders, it appears that the name is changed but when creating a subfolder the parent folder returns to its original name.

**Comment by trunkmaster** [comment]
@armm77 did you see that problem with Icon viewer or with Browser viewer also?

**Comment by armm77** [comment]
@trunkmaster Icon Viewer

**Comment by trunkmaster** [comment]
@armm77 Browser Viewer works correctly, right? 

At the moment I can see some exceptions while using Icon Viewer so renaming may be incorrect with Icon Viewer. I'll try to fix it.

**Comment by armm77** [comment]
@trunkmaster Yes, in browser view it works correctly.

**Comment by trunkmaster** [comment]
@armm77 latest commit should fix problem with Icon Viewer you've mentioned. Please test and tell me if you'll find more inconsitensies.

**Comment by armm77** [comment]
@trunkmaster, I confirm that the incident I reported no longer occurs, so I close the incident. 👍🏻
