### ISSUE TITLE
Bundle Gorm

### ISSUE THREAD

**Issue by bitigchi** [trunkmaster/nextspace#406]
Well, this is mostly out of my laziness, but that would be really to cool to have Gorm bundled.

As per my previous issue about localisation, I finally installed Nextspace, and it is great! I am so loving the UI paradigms and the interface itself. However, when I tried to ~install~compile Gorm, I found myself in a mess of libraries make errors everywhere. Although I've opted to install the developer tools, the required libraries for Gorm were not installed and could not get to install them manually (to be fair, didn't spend more than half an hour, but still too much time trying).

So, there I am. Is it possible to bundle Gorm with the developer install? I can also like a compiled binary in the meantime. :)

**Comment by trunkmaster** [comment]
@bitigchi, Gorm is bundled with nextspace-gnustep-devel package. It is installed in /Developer/Applications. Alternatively you can double-click on any .gorm file (it's bundle actually) and have it opened in Gorm.

**Comment by bitigchi** [comment]
It looks like the developer packages were not even installed at all during install. Anything possibly I am doing wrong?

I run the install script again just to be sure, but still no. It does not install.

**Comment by trunkmaster** [comment]
Install script should ask you if you want install developer's packages. You can try to install it manually.

**Comment by bitigchi** [comment]
It did ask me, and I complied, did the same whilst trying again just now.
