### ISSUE TITLE
Dependency errors whilst installing development packages

### ISSUE THREAD

**Issue by bitigchi** [trunkmaster/nextspace#408]
I am getting below dependency errors whilst trying to install development packages. I tried to install previous versions but had no luck.

![VirtualBox_CentOS_12_01_2022_21_18_54](https://user-images.githubusercontent.com/2769571/149199817-c07d5602-566f-4492-98bc-4afeed35f322.png)

**Comment by trunkmaster** [comment]
It seems you've tried to install NEXTSPACE on CentOS 8 - it lacks -devel packages mentioned. Try switch to CentOS 8 Stream and repeat NEXTSPACE install. 

BTW, CentOS 8 is EOL, so I plan to drop packaging NEXTSPACE for this distribution. CentOS 7 and Fedora will be supported as usual.

**Comment by armm77** [comment]
hi @bitigchi, I made an ISO installation image of CentOS Stream 8 to minimize installation problems.
 
https://github.com/armm77/nextspace-iso-installer
you can check if it works for you.

**Comment by bitigchi** [comment]
You are amazing. Just in time when CentOS 7 was driving me crazy not wanting to connect to network and Fedora 31 disappeared from the official site. I will try it out later on.

**Comment by felixding** [comment]
This is awesome! Finally there is an ISO!

@armm77 I assume it's X86-64 right? Asking on a M1 Mac.

**Comment by armm77** [comment]
hi @felixding, it is correct the iso is X86-64, in the future when the support for m1 is mature with stable distributions I could try it.

**Comment by felixding** [comment]
Are you talking about Asahi?

For now an ARM version of the ISO is good enough as I think most people would try NEXTSPACE in a VM first.

**Comment by trunkmaster** [comment]
@bitigchi have you resolved the issue? Do you still need help or case may be closed?

**Comment by bitigchi** [comment]
I will have access to this machine in February. Then I hope to try once more. Sorry for the delay.
