### ISSUE TITLE
Switch to LLVM/clang 7 and lastest GNUstep libraries

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#41]
Build LLVM/clang 7.0.1 packages

**Comment by trunkmaster** [comment]
LLVM and clang packages are created. All clang regression tests are successful.
I've experienced a corrupted build of LLVM because of missed sybmbolic link `libatomic.so` to `libatomic.so.1.0.0` in `/usr/lib64`.

**Comment by trunkmaster** [comment]
libobjc-2.0 was successfully built with:
```shell
$ cmake3 .. -DGNUSTEP_INSTALL_TYPE=SYSTEM \
                  -DCMAKE_C_COMPILER=clang \
                  -DCMAKE_CXX_COMPILER=clang++ \
                  -DCMAKE_C_FLAGS=-I/usr/NextSpace/include \
                  -DCMAKE_LIBRARY_PATH=/usr/NextSpace/lib \
                  -DTESTS=OFF -DCMAKE_BUILD_TYPE=Release
$ make
```
All test are passed.
`$ make test`
[tests output skipped]
`Total Test time (real) =  40.82 sec`
`100% tests passed, 0 tests failed out of 162`

**Comment by armm77** [comment]
👍
