### ISSUE TITLE
Keyboard Input problems

### ISSUE THREAD

**Issue by shellczok** [trunkmaster/nextspace#414]
Hi! I've managed to install Nextspace on a fedora 35 by following the instructions in the "build" section of the wiki. I must say that I'm super-impressed, and I'd love to use it as my preferred environment. Problem is that I'm unable to use the keyboard in any other applications except for the ones provided by the install, eg. Terminal.app, TextEdit.app etc. Any other applications are unresponsive to key inputs.

**Comment by trunkmaster** [comment]
@shellczok do you still have problems with keyboard? Please try current codebase - a lot of bugs were fixed...
