### ISSUE TITLE
Packaging/Sources build scripts - file not found for .h files

### ISSUE THREAD

**Issue by shogo2040** [trunkmaster/nextspace#415]
5_build_libs-gui.sh
Build with 1 error: NSTextCheckingClient.h:93:29 error: expected a type

6_build_libs-back.sh
Fatal error: ‘AppKit/AppKitExceptions.h’ file not found

7_build_Frameworks.sh
./OSEPower.h:32:10: fatal error: ‘upower.h’ file not found
#include <upower.h>

8_build_Applications.sh
Login.m:32:9: fatal error: ‘AppKit/NSPopUpButton.h’ file not found
#import <AppKit/NSPopUpButton.h>

Anything tips?

**Comment by trunkmaster** [comment]
@shogo2040 I need more information to investigate. What Linux distribution do you use? What version of clang you have installed? Have you installed required packages?

**Comment by trunkmaster** [comment]
@shogo2040 could you please try again and report results back?
