### ISSUE TITLE
Build failure on Fedora 36 on 0.build_libraries.sh script

### ISSUE THREAD

**Issue by ngoomie** [trunkmaster/nextspace#418]
Hello! I was trying to build NeXTSTEP on a relatively fresh Fedora 36 install (it's been used for barely even a week and has few extra packages installed), and was greeted with these errors:
```-- Build files have been written to: /home/nu/rpmbuild/BUILD/swift-corelibs-libdispatch-swift-5.4.2-RELEASE/_build
+ make -j16
[  3%] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/data.c.o
[  6%] Generating ../dispatch/module.modulemap, ../private/module.modulemap
[ 10%] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/runtime.c.o
clang-14: error: optimization flag '-ffat-lto-objects' is not supported [-Werror,-Wignored-optimization-argument]
make[2]: *** [src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/build.make:76: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/data.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang-14: error: optimization flag '-ffat-lto-objects' is not supported [-Werror,-Wignored-optimization-argument]
make[2]: *** [src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/build.make:90: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/runtime.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 10%] Built target module-maps
make: *** [Makefile:136: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.xb95pM (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.xb95pM (%build)
================================================================================
 Building of Grand Central Dispatch library RPM FAILED!
================================================================================
Aborting...
```
Not quite sure what to do from here, so I would appreciate some help assuming this is a problem on my end. I'm also not really sure what other information would potentially be required here, so by all means tell me if something else is needed. I can also attempt to re-build and send _all_ the terminal output if desired. Thanks in advance for your time!

**Comment by daemonspudguy** [comment]
The dev is in Ukraine and hasn't been seen doing much since February due to the war.

**Comment by ngoomie** [comment]
Ah, I see. I hope they're doing alright, all things considering.

**Comment by mikedebian** [comment]
Before running that command, export these two commands

export CFLAGS="-Wno-error"

export CXXFLAGS="-Wno-error"

**Comment by trunkmaster** [comment]
@ngoomie I've improved building from sources scripts (Packaging/Sources). You may try to build it once more. One of the essential changes was switching to new version of dispatch and CoreFoundation sources. If you still have Fedora 36 you may try to buld it again and share your results.

NOTE: Packaging/RedHat scripts is not ready yet, but Packaging/Sources supports build on RedHat-based distribution. It doesn't build rpm packages, but make install of binaries and resources.

**Comment by trunkmaster** [comment]
@ngoomie ?

**Comment by trunkmaster** [comment]
No feedback for a long time - closing issue. Please reopen if needed.
