### ISSUE TITLE
Error building 6_build_libs-gui.sh

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#425]
On a clean installation of fedora 39, the following error occurs.

![Screen Shot 2024-02-08 at 11 26 38 PM](https://github.com/trunkmaster/nextspace/assets/3104815/a70bc0a6-c81c-4562-80bf-291f3f6c7ce3)

**Comment by trunkmaster** [comment]
Confirmed. It's a problem with system GIF library - GifQuantizeBuffer() is the private function which became unavailable at some version. There are 2 options:
1. Get NSBitmapImageRep+GIF.m from master branch of libs-gui.
2. Wait for new stable GNUstep release (base and gui) and switch to it.

**Comment by trunkmaster** [comment]
@armm77 while waiting for new stable gnustep-gui release I've applied a workaround - copying NSBitmapImageRep+GIF.m from master branch before build. Check it please.

**Comment by armm77** [comment]
@trunkmaster confirmed, the error was solved.
