### ISSUE TITLE
Having trouble building from source for Fedora 39

### ISSUE THREAD

**Issue by fkinosh** [trunkmaster/nextspace#426]
Hi, sorry to bother but I can't seem to get rid of these problem, I'm following the scripts inside the Packaging/RedHat/ folder but this error shows up. This is a Fedora 39 fresh install.

```
-- Build files have been written to: /home/fkinoshita/rpmbuild/BUILD/swift-corelibs-libdispatch-swift-5.4.2-RELEASE/_build
+ make -j8
[ 10%] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/runtime.c.o
[ 10%] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/data.c.o
[ 10%] Generating /home/fkinoshita/rpmbuild/BUILD/swift-corelibs-libdispatch-swift-5.4.2-RELEASE/dispatch/module.modulemap, /home/fkinoshita/rpmbuild/BUILD/swift-corelibs-libdispatch-swift-5.4.2-RELEASE/private/module.modulemap
clang: error: optimization flag '-ffat-lto-objects' is not supported [-Werror,-Wignored-optimization-argument]
clang: error: optimization flag '-ffat-lto-objects' is not supported [-Werror,-Wignored-optimization-argument]
make[2]: *** [src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/build.make:90: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/runtime.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/build.make:76: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/data.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 10%] Built target module-maps
make: *** [Makefile:136: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.7dI3Xr (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.7dI3Xr (%build)
================================================================================
 Building of Grand Central Dispatch library RPM FAILED!
================================================================================
Aborting...
Aborting...
```

Just lost access to my previous GitHub account so I apologize for not being my best right now!

**Comment by trunkmaster** [comment]
Hi, more up-to-date way to build is Packaging/Sources scripts. However there's still unfixed problem described in issue #425.

**Comment by fkinosh** [comment]
How can I get the 'NSBitmapImageRep+GIF.m' file from master? I already built it from master so that left me a bit confused.

**Comment by armm77** [comment]
This would be the file that Sergi suggests or wait for the gnustep project to release a stable version, that time is indefinite.

https://github.com/gnustep/libs-gui/blob/master/Source/NSBitmapImageRep%2BGIF.m

**Comment by armm77** [comment]
Hi @hmelder, We would be very grateful, if you can help the request.

**Comment by fkinosh** [comment]
Hi, apart from the `NSBitmapImageRep+Gif.m` file issue (which I could solve, thank you!), I'm getting this error when running Sources/9_build_Applications.sh:
```
Making all in Login ...
Making all in Preferences ...
Making all for bundle Login...
 Creating Login.preferences/....
 Compiling file Login.m ...
Login.m:44:9: fatal error: 'DesktopKit/NXTAlert.h' file not found
   44 | #import <DesktopKit/NXTAlert.h>
      |         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by armm77** [comment]
Hi @fkinosh, Verify that the 8_build_Frameworks.sh script has been executed correctly. 
The file path is /usr/NextSpace/include/DesktopKit/

**Comment by fkinosh** [comment]
Thanks, I got it working! I also encountered another issue, when logging in with Login it shows "Session finished with error. See console.log for details."

`console.log` file is empty though.

**Comment by armm77** [comment]
Hi @fkinosh, I see that it is another error, I suggest closing this incident and opening a new one with the new error, also that you follow the steps that @trunkmaster recommends in this case to try to solve the problem they are presenting.
https://github.com/trunkmaster/nextspace/issues/400#issuecomment-1016862947

**Comment by fkinosh** [comment]
Alright, thank you for all the help!

**Comment by trunkmaster** [comment]
@armm77 thank you for your help.
@fkinosh how have you started Login.app, with `systemctl start loginwindow` or manually?

**Comment by fkinosh** [comment]
@trunkmaster I did ran `setup_user_home.sh`. I've just taken a backtrace like mentioned in https://github.com/trunkmaster/nextspace/issues/400#issuecomment-1016862947 and added it to this [issue](https://github.com/trunkmaster/nextspace/issues/427).

I will check journalcrl as well!
