### ISSUE TITLE
Unable to get any sound

### ISSUE THREAD

**Issue by fkinosh** [trunkmaster/nextspace#428]
Hi, sorry for opening so many issues. I've been testing out everything and I noticed that sound isn't working.

Setting sound to 100% on `Preferences -> Sound Preferences` has no effect and nothing shows up on the playback section on the  `Preferences -> Sound Preferences -> Advanced` section.

Also couldn't find anything useful on `journalctl`.

**Comment by fkinosh** [comment]
Oh, when opening something with VLC it shows up an error saying:
```
Audio output failed:
The audio device "default" could not be used:
Host is down.
```

**Comment by trunkmaster** [comment]
@fkinosh copy `Core/os_files/etc/skel/.config` to home directory and add user to `audio` group.

**Comment by fkinosh** [comment]
@trunkmaster unfortunately that didn't work, by default Fedora 39 is using pipewire, would that cause this sort of problem?

**Comment by trunkmaster** [comment]
> @trunkmaster unfortunately that didn't work, by default Fedora 39 is using pipewire, would that cause this sort of problem?

Maybe. Check if you have PulseAudio installed.

**Comment by fkinosh** [comment]
Yeah, that was it! If anyone encounters this problem you just need to remove `pipewire` with `sudo dnf install pulseaudio --allowerasing` (`--allowerasing` for it to also remove pipewire to avoid conflicts).

Thank you for all the help @trunkmaster! :D
