### ISSUE TITLE
How can I start a Nextspace WM session under Debian12 GDM

### ISSUE THREAD

**Issue by sheffler** [trunkmaster/nextspace#438]
Hello

I created a new debian12 VM and tried building from source.  I am in a graphical Debian12 environment with Gnome/Wayland.

I think I successfully built all of the sources.   I can do "openapp Gorm" and it runs under the Gnome desktop.  I cannot figure out how to start a Nextspace desktop, however.

The lines below show what I did - starting with cloning the repository and then going into Packaging/Source.  All built well.  There were a few error messages I copied into the listing.

At this point, I"m not sure how to start a window session with the Workspace.  This is a graphical Debian12 environment.  It has four different login sessions
  - GNOME
  - GNOME Classic
  - GNOME Classic on Xorg
  - GNOME on Xorg

The Xorg ones do not seem to start.  If selected, they simply send you back to the login screen - as if it started something and exited.

- I tried creating a /usr/share/sessions/nextspace.desktop file
- and I created a /usr/bin/startNextspace file whose contents are from Packaging/Sources/extra/xinitrc
- and I removed ~/.xinit created by setup_user_home.sh

I can now select the Nextspace option from the login screen, but it doesn't work in the same way that "Gnome on Xorg" does not do anything.

That's it for now.  Not sure what avenue to try next.  I think the fact that I cannot start any Xorg sessions is significant.

```
    git clone git@github.com:trunkmaster/nextspace


    . debian-12.deps.sh

    ./0_build_libdispatch.sh
    ./1_build_libcorefoundation.sh
    ./2_build_libobjc2.sh
    ./3_build_core.sh
    ./3_build_tools-make.sh
    ./4_build_libwraster.sh
    ./5_build_libs-base.sh
        Unit gdomap.service could not be found (but it is there)
    ./6_build_libs-gui.sh
        Unit gpbs.service could not be found (but it is there)
    ./7_build_libs-back.sh

    ./8_build_Frameworks.sh
    ./9_build_Applications.sh
        Failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /lib/systemd/system/gdm3.service
        Created symlink /etc/systemd/system/default.target -> /lib/systemd/system/graphical.target

    # this needs to be run twice
    sudo ./setup_user_home.sh
    ./setup_user_home.sh


```

**Comment by sheffler** [comment]
Solved!

I tried a number of things, including booting into console mode and manually running "startx".  Xorg would not run.
So I removed /etc/X11/xorg.conf.d/20-intel.conf that the nextspace install had added.  So now x11 runs.

I see no evidence of the nextspace login manager.

It is the gdm manager and I have added a "nextspace" profile
that calls a script (/usr/bin/startNextspace) that has been created with the contents of nextspace/Packaging/Sources/extra/xinitrc and my ~/.xinitrc has been removed.

Don't know if this helps :-)  In short, all of the software built cleanly and the integration with the login manager is working.

![nextspace](https://github.com/user-attachments/assets/958503d2-557f-4215-9292-a583b0c330d6)

**Comment by trunkmaster** [comment]
> Solved!

Great! Thanks for the patience!

> I tried a number of things, including booting into console mode and manually running "startx". Xorg would not run. So I removed /etc/X11/xorg.conf.d/20-intel.conf that the nextspace install had added. So now x11 runs.

Thanks for the hint. I need to remove it as it probably obsolete.

> I see no evidence of the nextspace login manager.

There's clue in your previous post
```
Failed to enable unit: File /etc/systemd/system/display-manager.service already exists and is a symlink to /lib/systemd/system/gdm3.service
```
I've tested on the minimal Debian install, without even Xorg installed and didn't face this error. Obviously, in your case you have GDM as default display manager. Try disabling GDM and enabling Login with these commands as root user in console mode without Xorg running:
```
# systemctl disable gdm3.service
# systemctl enable /usr/NextSpace/Apps/Login.app/Resources/loginwindow.service
# systemctl start loginwindow
```

> It is the gdm manager and I have added a "nextspace" profile that calls a script (/usr/bin/startNextspace) that has been created with the contents of nextspace/Packaging/Sources/extra/xinitrc and my ~/.xinitrc has been removed.
> 
> Don't know if this helps :-) In short, all of the software built cleanly and the integration with the login manager is working.

With commands listed above you will get the Login application as default display-manager systemd service. You don't need any any scripts or .xinitrc in your home directory.

**Comment by sheffler** [comment]
Worked great.  Thanks.
