### ISSUE TITLE
Fail to build Workspace without running WM.configure first.

### ISSUE THREAD

**Issue by BertrandDekoninck** [trunkmaster/nextspace#6]
As I mentionned in my previous mail.

**Comment by trunkmaster** [comment]
Fixed in master. To check if it works for you, try this:
$ cd Applications/|Workspace
$ make distclean
$ cd WindowMaker
$ make distclean
$ cd ..
$ make

**Comment by BertrandDekoninck** [comment]
It works now. No need to run WM.configure anymore.

**Comment by trunkmaster** [comment]
Great. Closing issue.
