### ISSUE TITLE
 Fail to login with Login.app

### ISSUE THREAD

**Issue by BertrandDekoninck** [trunkmaster/nextspace#7]
Console message is: "Workspace :error while loading shared librarie: libWUtils.so.5:cannot open shared object: No such file or directory".

**Comment by trunkmaster** [comment]
Do you have .xinitrc file in user home directory?

**Comment by BertrandDekoninck** [comment]
Yes and it seems to be the one you should expect, It sources /etc/profile.d/nextspace.sh.

**Comment by BertrandDekoninck** [comment]
I managed to hav Wmaker starting by changing the following  in /etc/profile.d/nextspace.sh : 
`export LD_LIBRARY_PATH="$HOME/Library/Libraries" `
to 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$HOME/Library/Libraries`

But it seems that only wmaker is running : no Workspace window opens up, even if the top right GNUstep icon doesn't have the three dots of a non running app. I can open a Terminal and launch an instance of Workspace by hand.

**Comment by BertrandDekoninck** [comment]
Onee more thing : at session startup, not only Workspace doesn't open any viewer window, but it's displays a black alert dialog (nothing can be read and no button is visible, only the arrow on the uniique button). When I click on the arrow, the session is closed and Login.app pops again.

Here is the content of the GNUstepSecure file : 
`2017-12-02 20:30:10.621 Workspace[2085:2085] Starting Workspace Manager...
2017-12-02 20:30:10.625 Workspace[2085:2085] XRandR 1.5, event base:88, error base:145
2017-12-02 20:30:10.625 Workspace[2085:2085] NXScreen: randrUpdateScreenResources: START
2017-12-02 20:30:10.629 Workspace[2085:2085] NXScreen: randrUpdateScreenResources: END
2017-12-02 20:30:10.641 Workspace[2085:2085] Apply saved display layout...
2017-12-02 20:30:10.641 Workspace[2085:2085] Apply automatic default display layout
2017-12-02 20:30:10.641 Workspace[2085:2085] VGA-1: become main display.
2017-12-02 20:30:10.641 Workspace[2085:2085] NXScreen: New screen size: {width = 1208; height = 595} ({width = 200; height = 200}), old {width = 800; height = 600}({width = 200; height = 200})
2017-12-02 20:30:10.642 Workspace[2085:2085] VGA-1: Set resolution {width = 0; height = 0} and origin {x = 0; y = 0}
2017-12-02 20:30:10.642 Workspace[2085:2085] NXScreen: set new screen size: START
2017-12-02 20:30:10.642 Workspace[2085:2085] NXScreen: set new screen size: END
2017-12-02 20:30:10.654 Workspace[2085:2085] NXScreen: set resolution to VGA-1: START
2017-12-02 20:30:10.654 Workspace[2085:2085] VGA-1: Set resolution {width = 1208; height = 595} and origin {x = 0; y = 0}
2017-12-02 20:30:10.654 Workspace[2085:2085] VGA-1: no CRTC assossiated with Output - requesting free CRTC...
2017-12-02 20:30:10.661 Workspace[2085:2085] NXScreen: set resolution to VGA-1: END
2017-12-02 20:30:10.661 Workspace[2085:2085] setGammaFromDescription: 0.800000 : 0.800000 : 0.800000
/usr/NextSpace/Apps/Workspace.app/Workspace(get_icon_filename(WindowMaker/src/wdefaults.c:399)): warning: icon "recycler.tiff" doesn't exist, check your config files
2017-12-02 20:30:11.879 Workspace[2085:2085] NXScreen: randrUpdateScreenResources: START
2017-12-02 20:30:11.882 Workspace[2085:2085] NXScreen: randrUpdateScreenResources: END
/usr/NextSpace/Apps/Workspace.app/Workspace(handle_inotify_events(WindowMaker/src/event.c:364)): warning: Inotify: Reading config files in defaults database.
2017-12-02 20:30:12.050 Workspace[2085:2085] NSColor.m:273  Assertion failed in void initSystemColors().  couldn't get default system color selectedKnobColor
2017-12-02 20:30:18.909 Workspace[2085:2085] NXScreen: received NXScreenDidChangeNotification inside Workspace Manager. Skip updating XRandR screen resources. Assuming it's already done.
/usr/NextSpace/Apps/Workspace.app/Workspace: Uncaught exception NSInternalInconsistencyException, reason: NSColor.m:273  Assertion failed in void initSystemColors().  couldn't get default system color selectedKnobColor
Stopping GNUstep services: gpbs gdnc.
.`

When I said in the previous message that I could open an instance of Workspace, it's obviously another instance running beside that first instance. If I close the alert dialog, the other opened  apps (Terminal, or the second Workspace)  still run but I lose the window manager and Login.app pops up beside them.

**Comment by trunkmaster** [comment]
It's strange. Show me yout .xinitrc file.

**Comment by BertrandDekoninck** [comment]
This is in a clean CentOS 7 virtual machine, with your rpms installed, frameworks and apps  built from source. No other libraries.
xinitrc hereafter : 
[xinitrc.txt](https://github.com/trunkmaster/nextspace/files/1532699/xinitrc.txt)

**Comment by trunkmaster** [comment]
Thank you. Everything is correct. I roll to snapshot of my VM and reinstall rpms and build sources. I've got other strange behaviour of Login: nothing is started and no messages in console. I need to review user session creation code in Login. Hold on.

**Comment by trunkmaster** [comment]
@BertrandDekoninck, I've played around with different configurations and came to the following conclusions: 1. SELinux must be disabled. 2. Your problem is definitely dynamic linker problem.
So, please, check the existance and contents of file /etc/ld.so.conf.d/nextspace.conf.

**Comment by BertrandDekoninck** [comment]
SELinux is disabled.
And the /etc/ld.so.conf.d/nextspace.conf  contains the following : 
```
/Library/Libraries
/Developper/Libraries
/usr/NextSpace/lib
```
I don't know how we use that file in CentOS but my $LD_LIBRARY_PATH should contain the directories that are listed inside, which it still doesn't.

Anyway this may be unrelated. I've reverted the change in /etc/profile.d/nextspace.sh and the loginwindow service still runs fine. No more "error while loading shared librarie" error.  Maybe some reboot was necessary.

Workspace still doesn't run properly though.

**Comment by trunkmaster** [comment]
Bertrand, files inside /etc/ld.so.conf.d used by system dynamic linker. Command ldconfig creates chache file /etc/ld.so.cache. Something wrong with it. Try to remove /etc/ld.so.cache and run 'ldconfig'.
Can you unset $LD_LIBRARY_PATH and check the output of command 'ldconfig -p | grep NextSpace'? What libraries do you see?

**Comment by trunkmaster** [comment]
@BertrandDekoninck, do you have any progress? Did you try to reinstall everything from scratch?

**Comment by BertrandDekoninck** [comment]
Hi, Sergii,

I don't see any progress. I had updated my clone of your repo to the 
following commit : 5c6dd3fe4393f111348b81b0a07ab6bc34e00867.

I won't be able to reinstall from scratch until a few days (and then 
I'll do a snapshot of my clean system). Should I install the same rpms 
again and then build the rest, or should I build everything fromscratch ?

Bertrand

Le 13/12/2017 à 12:04, Sergii a écrit :

**Comment by trunkmaster** [comment]
Hi Bertrand,

Try to reinstall the same RPMs and rebuild the Frameworks and Applications. After that run 'ldconfig' as root. 
I can't reproduce result you've reached. This is not my bug.

**Comment by BertrandDekoninck** [comment]
Bad news. I've set up a new virtual machine in virtualbox and I get the same bug but no more LD_LIBRARY_PATH problem.  This is on debian 8 64 bit, with Virtualbox 5.2.2. Here are the install notes : 

CentOS7 and NEXTspace 64bit install in Virtualbox-5.2.2 (in debian 8 64bit)


1) Standart installation in Virtualbox. IOAPIC disabled (because machine freezes with them). I didn't install VBox additions

2) Disable SELinux in /etc/sysconfig/selinux and reboot.

3) Add elrepo-release rpm and install libbsd from that. 

4) Download nextspace released rpms from github/trunkmaster/nextspace. 
   Install dependancies as root : yum install zsh libart_lgpl. 
   Install the nextspace rpms with "rpm -ivh" as root

5) Clone nextspace git repo in ~/NEXTspace_Install/  Warning : I'll have build errors at link time if the nextspace repo is in a folder which has a space character in its path :
   git clone https://github/trunkmaster/nextspace

6) Reboot to be sure the environnement variables are correct for all users.

7) Compiling Frameworks :
   - Install dependancies as root with :
      yum install file-devel libX11-devel libxkbfile-devel libXrandr-devel libXCursor-devel upower-devel libudisks2-devel libdbus-glib-devel libXmu-devel libXft-devel libpng-devel libtiff-devel giflib-devel libwebp-devel libjpegturbo-devel libexif-devel pam-devel libXinerama-devel
    - build as normal user with "make"; then as root "make install".

10) Compiling apps :
    Linker fails to find libobjc-4.6; don't forget to run ldconfig as root before building apps.
    I've run ldconfig after the install of the apps.

11) Create user "me" with "adduser me " as root; add it to the wheel group with "usermod -aG wheel" as root 

12) Create /usr/Nextspace/Preferences and copied Login.app/Resources/Login inside

13) Install the loginwindow.service from Login.app/Resource as root :
    systemctl enable /usr/Nextspace/Apps/Login.app/Resources/loginwindow.service
  Weird : I always encounter an error there, telling that the file exists even if it doesn't. After that command, the service is installed correctly in /etc/systemd/system/

14) Stop the gdm service as root :
    service gdm stop.

15) Start the loginwindow service as root to launch Login.app :
    service loginwindow start

Then I encounter the same bug ; Workspace fails to launch with a black alert panel. But there is no need to change the LD_LIBRARY_PATH in the profile file, as in the beginning of this thread.

I'll further try to create a session in gdm to launch workspace to see if it runs well. The Login.app problem seems to be gone. But Workspace seems to catch an exception.

**Comment by trunkmaster** [comment]
@BertrandDekoninck some notes/questions for steps you kindly described:
step 1: Have enabled 3D acceleration in VirtualBox? 
step 4: you don't need to install dependencies for RPMs manually. Just use "yum localinstall *.rpm" inside directory where you've downloaded NEXTSPACE RPMs.
step 8: I've never seen such message on my system. I feel this is the root cause of a problem. Have you installed libobjc2 RPM from my github page or you use other libobjc? Have you installed clang and llvm?
step 10: is not needed anymore. I've fixed it in master branch.
step 12 and 13: 'sevice' command is obsolete. It is for managing SysV init scripts. Use "systemctl start" and "systemctl stop" instead.

What is the contents of user's 'console.log' after logon? It is at /tmp/GNUstep<UID>/console.log.

**Comment by BertrandDekoninck** [comment]
Sorry for the delay. I was quite away from this with  Christmas and New Year . Happy new one by the way.
So here are a few answers : 
step 1 : gnome install (but I may have selected some development package at install too). No Virtualbox guest driver but the 3d acceleration was on in it. I've tried without it and get the same error.. 
step 3 : I really mean elrepo-release. See  http://elrepo.org/tiki/tiki-index.php
step 4 Good to know
step 7 : it should be typos from myself. autoconf and automake were already installed
step 8 : of course it's your libobjc, clang and llvm. So are you thinking Workspace didn't link correctly at build time ? How could I check this ?


I've managed to create a working nextspace.desktop file to launch Workspace  with the gdm chooser. And I encounter the same error as in Login.app : Workspace doesn't launch properly  and shows a black alert dialog. And no console.log file is created in /tmp. 
But Login.app really seem to be out of the problem now.

I tried to debug Workspace with a gdm session which only launch an xterm without any window manager. Inside I can launch Workspace and encounter the same error. If I try to run "debugapp Workspace.app" in that xterm, wmaker seems to start, two appicons are visible (Workspace and Xterm) but no Workspace window opens up. Then I'm stuck because there is no right click menus. wmaker and gdb  seem to be stuck. In fact, the last message in my xterm is  
" wmsetbg(getValueForKey(wmsetbg.c:1026)) : "warning : could not open domain file /Users/me/GNUstep/Preferences/.WindowMaker/WindowMaker"

**Comment by trunkmaster** [comment]
Hi, 
Could you please send me screenshot of your screen after logon? Use Login instead of gdm please. Workspace's internal WindowMaker gets config file path prefix from GNUSTEP_USER_ROOT environment variable. It should be set to "$HOME/Library" with standard install. That's what Login app does before Workspace session starts.
It would be great if you send me some logs also ('journalctl -x /usr/NextSpace/Apps/Login.app/Login' and /tmp/GNUstep*/console.log).
Another possible way is to install VBox guest additions and check again.

**Comment by BertrandDekoninck** [comment]
I'll send them directly because I don't see how to make attachment when commenting this issue on github.

**Comment by trunkmaster** [comment]
Finally I've managed to reproduce the bug and found cause of a problem.
If locale variable LC_NUMERIC holds other than "en_US.UTF-8" value (uk_UA.UTF-8 in my case) Workspace starts with black panel you've described.
I need to find what the real root cause and why it affects Workspace (for example, you can start Terminal without a problem).

Please set this variable to "en_US.UTF-8" and try to launch Workspace after that.
Check your system locale value of LC_NUMERIC ('locale' command as root) if you want Workspace to be launched with Login.

**Comment by trunkmaster** [comment]
My further analizing of a problem showed me that it's likely multithreading side effect (I mean LC_NUMERIC value effect). I need more investigation.

**Comment by trunkmaster** [comment]
Hi Bertrand,
Please try the latest code. I've changed Workspace's startup sequence and made some enhancements.
Check it out and let me know about results.

**Comment by BertrandDekoninck** [comment]
I seems to work like a charm. No more black window with my locale. Great job ! 
One thing though : after the login sequence, we end up with a Preferences main menu. Focus should be given to Workspace instead.
Bertrand

**Comment by trunkmaster** [comment]
Yes, I forgot to add '-NXAutoLaunch YES' parameter to Preferences and TimeMon dock icons. You still can do it by yourself (just quit app, right click on dock icon, select "Settings..." menu item and add this parameter to "Application path and arguments" field). 
In future this parameter will be added by Workspace to docked applications which configured as autolaunched in Workspace preferences.
Is this issue can be considered as "Closed"?

**Comment by BertrandDekoninck** [comment]
Le 29/01/2018 00:25, Sergii a écrit :
> Yes, I forgot to add '-NXAutoLaunch YES' parameter to Preferences and
> TimeMon dock icons. You still can do it by yourself (just quit app,
> right click on dock icon, select "Settings..." menu item and add this
> parameter to "Application path and arguments" field).
> In future this parameter will be added by Workspace to docked
> applications which configured as autolaunched in Workspace preferences.
> Is this issue can be considered as "Closed"?
>
Of course, yes !
Bertrand
