### ISSUE TITLE
OpenStep style "menu button" behavior

### ISSUE THREAD

**Issue by ratmice** [trunkmaster/nextspace#8]
As was discussed a bit on the gnustep lists,  I'm not sure if it is something you want to support or not, but I have always liked the behavior of the OpenStep "menu button",
however few window managers professing *step like behavior have ever behaved as such,
I made a video which shows how it behaves when clicking on various things for which wmaker
may bring up various menus.

https://youtu.be/1_glOOYIGlc

I would summarize it as such:
when an event from the menu button is received by the window manager
the event is redirected to the currently active application (selected window?).

Integrating such behavior into the window manager is not terribly difficult,
but from the application side, few applications behave correctly when receiving a random button event outside of any of their window extents.

Integrating this behavior with non step X applications is a bit troublesome as well.
My general thought is that using an X property (to randomly make one up) _NEXTSPACE_MENU_EVENTS=1 for windows to opt in menu event redirection,

when a window with _NEXTSPACE_MENU_EVENTS=1 is the currently focused window,
all menu button events will be forwarded to that window.

This unfortunately means that behavior would change depending upon the currently selected window,
rather than being uniform.  But allows one to avoid sending windows events which they will not understand.

What to do when the property is unset, or zero is up for debate, the options i see are:
1. Suppress the event
2. Send the event to the window the mouse is over
3. Build a minimally useful menu for X applications which e.g. populates the "Windows" submenu,
display that on menu button event.
4. Check if focused window class is GNUstep and make desicion to redirect event or show Workspace application menu (as option: show WindowMaker root menu if Menu Button disabled in Preferences).

that will probably be something that has to be played with to discover if any option is acceptable.
option 3 Seems the most consistent if it is feasible, but also probably the most difficult,
I'm guessing workspace would have to generate a rather dynamic menu and populate it for each window group

If this is something that is agreeable to you, perhaps I could look into it more.
as I have written a window manager which implements the first part (event redirection), somewhere..

**Comment by armm77** [comment]
Interesting proposal, it is better to suppress the event.

**Comment by trunkmaster** [comment]
@ratmice my first experiment shows me no trouble for mouse button event redirection. To be more specific:
- I've implemented right mouse button press/release event redirection to active (focused) window if right mouse button event occurs on root window in WindowMaker part of Workpace;
- GNUstep application shows it's app menu right under cursor, on button release app menu disappears;
- X applications does nothing. No errors in console. I've checked Emacs, Firefox, GIMP.
What applications did you have troubles with? What X11 errors did they produce?
I've not pushed any changes to repo yet.
Anyway, I have another solution/proposal: check if focused window class is GNUstep and make desicion to redirect event or show Workspace application menu (as option: show WindowMaker root menu if Menu Button disabled in Preferences).

**Comment by ratmice** [comment]
@trunkmaster cool, IIRC (it has been a number of years)

the issues i was seeing were:

- GNUstep application menu not dissapearing under some circumstances (single clicking, or mouse up outside of the window perhaps)
- segfault in firefox(?), perhaps valgrind caught this and it was fixed in the mean time
- extraneous logging when running from terminal w/ gnome applications,

Will edit your additional proposal into the top issue.

**Comment by trunkmaster** [comment]
@ratmice now changes are in the master. You need to reinstall Workspace. Also, I've changed Preferences-Mouse to enable/disable desktop menu (not inwindow app menu yet).
Try it and tell me what do you think.

**Comment by trunkmaster** [comment]
@ratmice Desired behaviour implementation completed.
Changed components are: Frameworks:NXSystem, Applications: Preferences and Workspace.
Please, reinstall and test. I'm waiting for your feedback.

**Comment by ratmice** [comment]
@trunkmaster sorry for the delay (distro doesn't have all the dependencies), trying to get that sorted out
look forward to trying it out, hopefully i can get it all sorted before holiday travels.

**Comment by trunkmaster** [comment]
@ratmice No problem. I'm waitng for your comments before closing the issue.

**Comment by trunkmaster** [comment]
@ratmice, Do you have any news? Did you try it?

**Comment by ratmice** [comment]
I have attempted to, but haven't manage to get it to build via RPM,
i managed to build it manually but something went awry, and windowmaker starts up,
but doesn't function correctly.

if you are happy that the issue is fixed by all means close, when I get it working i can reopen or open another issue perhaps.  Sorry that i have not managed to get it working.

**Comment by trunkmaster** [comment]
Current implementation fits me. Of course, there are still many places in Workspace for fixing and polishing. I plan to make an intensive Workspace testing. I close this issue.
Please file separate issue if you have some awkward behaviour of Workspace.
